### ISSUE TITLE
Login Issue: turn on JavaScript in Browser Settings

### ISSUE THREAD

**Issue by E-Ducky** [Tustin/PlayStationDiscord#1]
[Image of Issue](https://i.imgur.com/0xqJsjs.png)

Appears in a separate window when I click "Sign in with Playstation".

My default browser is Chrome with JavaScript enabled. I changed the default to Internet Explorer and tried again but still no luck. Running Windows 7 Ultimate.

**Comment by Tustin** [comment]
Strange. The Web Browser control uses IE 7 or something ancient like that. The only idea I have is maybe seeing if Javascript is disabled in your version of Internet Explorer/Edge.

**Comment by Tustin** [comment]
https://social.msdn.microsoft.com/Forums/windows/en-US/3264223f-d5c0-4c1a-b550-3621ca17635f/webbrowser-javascript-issue?forum=winforms this is how you can enable Javascript for Internet Explorer

**Comment by E-Ducky** [comment]
Fantastic, Tustin. I didn't have active scripting enabled. Thank you.
