### ISSUE TITLE
Game icons don't work for non-North Americans

### ISSUE THREAD

**Issue by ThaTiemsz** [Tustin/PlayStationDiscord#10]
Since most if not all CUSA's are different in the European, Asian and Japanese PlayStation Stores than the ones from the American PlayStation Store.

**Comment by Tustin** [comment]
Thanks for the heads up. I'll try to add some games for those regions too.

**Comment by Tustin** [comment]
Resolved this in 2.1.0.0 by using the game name to identify different regions.
