### ISSUE TITLE
An error has occurred while communicating with discord

### ISSUE THREAD

**Issue by Zolaida** [Tustin/PlayStationDiscord#109]
I guess this has been an issue for months at this point , at least for PS3 users.
Is it gonna be fixed?

![Screenshot_3](https://user-images.githubusercontent.com/38325920/92183369-11aea100-ee46-11ea-88d6-c23176ab2b85.png)

**Comment by vfssant** [comment]
same here
![image](https://user-images.githubusercontent.com/60822730/92503199-4a000780-f1d7-11ea-9adc-c48cf6f24027.png)

**Comment by xetsubou** [comment]
no signs of it being fixed

**Comment by Jump-Suit** [comment]
Getting this issue as well I would LOVE to display my PS3 game status again...

**Comment by xetsubou** [comment]
same, I have lost the urge to play ps3 because of this lol

**Comment by CoungToElf** [comment]
even happens for ps4 games now for me
![image](https://user-images.githubusercontent.com/72817735/95997383-ba66fd80-0e01-11eb-802e-6565145ad48d.png)

**Comment by BayGamerYT** [comment]
![image](https://user-images.githubusercontent.com/60859158/96531354-b8100380-1246-11eb-947f-25fe4fecd1d2.png)

**Comment by EdSG** [comment]
It's happening on the macOS version as well.
![Screen Shot 2020-10-21 at 8 45 34 AM](https://user-images.githubusercontent.com/2864845/96744460-ea6e4d80-1379-11eb-85ef-c10cc6309653.png)

**Comment by that1estonian** [comment]
Got the error when i closed a game on PS4

**Comment by Tustin** [comment]
This was most likely broken because of an issue with PS3/Vita titles which was fixed in 3.2.0, but since it appears to happen sometimes with PS4 titles as well I'll keep this open. It's always possible that this happens when Discord goes down or maybe a bad response with the PSN API. I'll need to see the log file for more details (%APPDATA%/PlayStationDiscord/log.log

**Comment by madridplayz** [comment]
its happening to me but on ps4 pls help

**Comment by madridplayz** [comment]
> even happens for ps4 games now for me ![image](https://user-images.githubusercontent.com/72817735/95997383-ba66fd80-0e01-11eb-802e-6565145ad48d.png)

me to

**Comment by tovade** [comment]
@Tustin 
![image](https://user-images.githubusercontent.com/66245404/147603072-28411a6e-3799-4341-b917-72271e059de7.png)

**Comment by tovade** [comment]
![image](https://user-images.githubusercontent.com/66245404/147603223-320dba30-fdd3-468e-9d8d-aef343c758dd.png)
seems like discord-rpc is closing the connection 🤔

**Comment by Tustin** [comment]
> @Tustin ![image](https://user-images.githubusercontent.com/66245404/147603072-28411a6e-3799-4341-b917-72271e059de7.png)

It's failing to resolve http://m.np.playstation.net/ for some reason. What happens when you try to go to that URL in your browser? It should look something like this:
![image](https://user-images.githubusercontent.com/5008148/147603355-1c8e19b7-84f8-4b6b-8a90-eddb7f5d3cb0.png)

**Comment by tovade** [comment]
no, after a few minutes i realized that was when i was offline, the package "discord-rpc" is the main issue here
