### ISSUE TITLE
Crashes after login

### ISSUE THREAD

**Issue by ImHiiro** [Tustin/PlayStationDiscord#11]
I proceed normally until I input my 2FA code and login, after that window closes, the app crashes.
There's a log.txt and tokens.dat file in AppData/Roaming/PlaystationDiscord (been checking the rest of the threads).

Edit: here are the event viewer logs.
https://pastebin.com/6m0Z8aBs
https://pastebin.com/y79DMEwx

**Comment by Tustin** [comment]
Do you have an avatar on PSN? It seems like it's crashing when it's trying to download an image, but the only image I attempt to download is your avatar.

**Comment by ImHiiro** [comment]
Yeah, I have one, purchased avatars are an issue?

**Comment by ImHiiro** [comment]
Does it matter if my account is EU? @Tustin

**Comment by Tustin** [comment]
It shouldn't but I'll be done with a new version very soon (just need to fix some things) that adds a bit more checking to prevent random crashes like this from happening. After I release that you can try it again to see if you still have issues.

**Comment by Tustin** [comment]
Just drafted the new version. Feel free to try it whenever you can to see if it fixed your issue. If you still have problems, let me know 😄.

**Comment by ImHiiro** [comment]
Still crashing, though it might actually a problem on my end. @Tustin 

https://pastebin.com/DFaE8BE6
https://pastebin.com/0Mp3DkBk

Will let you know if it's actually my bad 😐

**Comment by Tustin** [comment]
That's really strange. The callstack still indicates that it's crashing when trying to either download the image or setting the image on the form. I added checks to ensure that it actually found your avatar so at this point I think it has to do with your avatar (but I doubt it), or it could be something on your PC. Could you send me the link to the avatar you use just in case?

**Comment by ImHiiro** [comment]
@Tustin 

I've been searching and the kernelbase.dll caught my attention, I might have to reinstall W10 since it's always appearing on the event viewer's log, and seems like it might've been corrupted (at least that's what all the posts I checked said).

My avatar it's this one: https://store.playstation.com/en-gb/product/EP0700-CUSA06014_00-AV00000000000003 (it should redirect you to your store).

**Comment by ImHiiro** [comment]
After a few scans, 3 DISMs and sfc /scannow, it's working!
Well, kinda... I can login, but the game won't appear.

![image](https://user-images.githubusercontent.com/40962597/48876871-6f503580-edf8-11e8-8808-cb702555bd27.png)
@Tustin

**Comment by ImHiiro** [comment]
Update: it's working, ran it as administrator and I can finally see everything!

**Comment by Tustin** [comment]
I just released the newest version of PlayStationDiscord which has been completely rewritten and should fix any previous issues: 
https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.0

Just download `installer-PlayStationDiscord-3.0.0.exe` if you use Windows or `PlayStationDiscord-3.0.0.dmg` if you use Mac!
