### ISSUE TITLE
Documentation bug? - What does this project do?

### ISSUE THREAD

**Issue by xdhmoore** [Tustin/PlayStationDiscord#110]
Hello,

I'm perusing the project, but I can't figure out what it does. I thought from the name that it would run on a PlayStation somehow and update Discord's Rich Presence api with the "currently playing" status, but it seems to run on Linux/macOS/PC. Where does the PlayStation come in? Is it connecting to a PlayStation, or maybe these are PlayStation games running on a laptop/desktop? Or maybe it's a client to display on a laptop/desktop the statuses of specifically PS games?

Thanks.

**Comment by LadySmith** [comment]
It logins to Playstation Remote to get details.

[Check here](https://github.com/Tustin/PlayStationDiscord/blob/development/src/PlayStation/Account.ts)

**Comment by xetsubou** [comment]
It's broken and dead

**Comment by LadySmith** [comment]
> It's broken and dead

What's wrong with your program though? PS3?

Don't know anything about PS3 but I do run my own instance with my own gamelist repo and still works for PS4. Not getting credit for it just running my own gamelist 'cuz normal one just includes most popular ones due to discord image limits.

**Comment by DarkGhost5** [comment]
> > It's broken and dead
> 
> What's wrong with your program though? PS3?
> 
> Don't know anything about PS3 but I do run my own instance with my own gamelist repo and still works for PS4. Not getting credit for it just running my own gamelist 'cuz normal one just includes most popular ones due to discord image limits.

May I ask how do you do it? Normal one doesn't include most of the games I play, is there a way to do your own list?
