### ISSUE TITLE
Not able to establish a server connection 

### ISSUE THREAD

**Issue by TheBrokenRoomba** [Tustin/PlayStationDiscord#112]
Hi I'm using a mac and when im trying out this amazing application it fails to connect to the server 

The error code I keep getting is (18.bef31502.16041933.90d91a4)

**Comment by Gregory280** [comment]
I'm having this same issue. I'm using the appimage for Linux.

**Comment by Tustin** [comment]
This is a Sony issue and unfortunately nothing I can do. It seems to randomly work sometimes for no known reason. I recommend to keep trying, maybe try clearing cache/cookies in Firefox/Edge/Chrome to see if it helps. Some more discussion can be found in #80.
