### ISSUE TITLE
thanks for ps5 stuff

### ISSUE THREAD

**Issue by xetsubou** [Tustin/PlayStationDiscord#114]
its cool you added ps5 stuff but alot of us still use ps3? which is broken

**Comment by Tustin** [comment]
I don't have a PS3 that can go online anymore so someone is going to need to fork it and try to figure out what is wrong with it. I can look at the API but there's no promise I can fix whatever might be wrong with it.

**Comment by asc3ns10n** [comment]
I believe the issue is that the PS3 (and Vita) Discord apps are gone/inaccessible. It works fine if I use my own app ID.

**Comment by Maxii1** [comment]
I have ps4 and no pc. Just i want for download from my phone

**Comment by Tustin** [comment]
@asc3ns10n Thanks -- I believe you are correct. I'll make new applications for those and it should work again in the new update.

**Comment by Tustin** [comment]
Fixed with 3.2.0.
