### ISSUE TITLE
PS5 support

### ISSUE THREAD

**Issue by KKiruano** [Tustin/PlayStationDiscord#117]
Hey there, not sure if it's a bug or if it just isnt implement yet but it doesnt detect any ps5 activity.

**Comment by G3e** [comment]
I've got the same issue.

**Comment by Doglegs2130** [comment]
same

**Comment by NickosDim** [comment]
Same here. It shows me as offline at the windows 10 app

**Comment by Tustin** [comment]
Added with version 3.2.0.
