### ISSUE TITLE
Clicking New Update only downloads Old, which still asks to download new update

### ISSUE THREAD

**Issue by neilchow2** [Tustin/PlayStationDiscord#124]
**Information**
- OS: Windows / macOS / Linux (Ubuntu, Debian, etc...)
- Version: Latest

**Describe the bug**

**Log**
Provide the bottom (or all) of your log file for PlayStationDiscord.
- Windows: `%APPDATA%\PlayStationDiscord\log.log`
- macOS: `~/Library/Logs/PlayStationDiscord/log.log`
- Linux: `~/.config/PlayStationDiscord/log.log`
```
[log contents]
```

**Additional context**

**Comment by JonA-01** [comment]
@neilchow2 You can download the most up-to-date versions (and any future versions) on the [release page](https://github.com/Tustin/PlayStationDiscord/releases) of the project. This will solve your issue. The website probably hasn't been updated yet.
