### ISSUE TITLE
 Is playing Console, which should be Is playing Game.

### ISSUE THREAD

**Issue by xtrasmal** [Tustin/PlayStationDiscord#125]
**Is your feature request related to a problem? Please describe.**
No problems, just annoying you can't see the title straight away.

**Describe the solution you'd like**
The title show: _Is playing Playstation 4_, which should be _Is playing Super Mario_.

**Additional context**
![image](https://user-images.githubusercontent.com/1174877/101326004-eedcc000-386c-11eb-8a5e-4a1c28ef5e21.png)

**Comment by asc3ns10n** [comment]
I don't think this is possible, and based on the discussion [here](https://github.com/discord/discord-rpc/issues/54) it doesn't seem like Discord is really interested in working on it.

**Comment by xtrasmal** [comment]
of course it is possible.  I have it working locally. You just have to render the text for Playstation on the location of the game and the other way around.

**Comment by asc3ns10n** [comment]
I'm not sure what you mean. The name of what you're playing is derived from the application name. I don't see anything in the rich presence or game sdk where you can set the name.

**Comment by Deltara3** [comment]
This wouldn't be humanly possible, each console is its own Discord application. To have to say what game you are playing, you would need an individual Discord application for each game, it would be a waste of time to do. Hence why it says playing console.

**Comment by wyntrr-end** [comment]
I came here about this same suggestion. I'm not sure why people are saying that this isn't possible, since the app clearly demonstrates that the title "Playing PlayStation 4" can be changed: playing on PS5 or PS3 changes the title accordingly, without the need to launch a separate application.

**Comment by asc3ns10n** [comment]
> I came here about this same suggestion. I'm not sure why people are saying that this isn't possible, since the app clearly demonstrates that the title "Playing PlayStation 4" can be changed: playing on PS5 or PS3 changes the title accordingly, without the need to launch a separate application.

The title is changing by switching to a different Discord application ID. Having separate application IDs for each game is the only way this can be done atm, which is not feasible considering the application limit is 25 per account.

**Comment by wyntrr-end** [comment]
Okay, that makes sense. I was not aware that that was the case.

**Comment by xtrasmal** [comment]
> > I came here about this same suggestion. I'm not sure why people are saying that this isn't possible, since the app clearly demonstrates that the title "Playing PlayStation 4" can be changed: playing on PS5 or PS3 changes the title accordingly, without the need to launch a separate application.
> 
> The title is changing by switching to a different Discord application ID. Having separate application IDs for each game is the only way this can be done atm, which is not feasible considering the application limit is 25 per account.

You can call it PSN, which covers all.

**Comment by asc3ns10n** [comment]
> > > I came here about this same suggestion. I'm not sure why people are saying that this isn't possible, since the app clearly demonstrates that the title "Playing PlayStation 4" can be changed: playing on PS5 or PS3 changes the title accordingly, without the need to launch a separate application.
> > 
> > 
> > The title is changing by switching to a different Discord application ID. Having separate application IDs for each game is the only way this can be done atm, which is not feasible considering the application limit is 25 per account.
> 
> You can call it PSN, which covers all.

I'm not sure how that would help, since there isn't a way to dynamically change the application name (that isn't API abuse).

**Comment by xtrasmal** [comment]
@asc3ns10n @Deltara3 @Tustin @wyntrr-end 
https://www.sie.com/en/blog/announcing-playstations-new-partnership-with-discord/
