### ISSUE TITLE
Offline Bugs

### ISSUE THREAD

**Issue by GuiGui73YT** [Tustin/PlayStationDiscord#126]
When I launch the application it tells me that I'm offline while I'm playing on my PS3.
Is this normal?
![20201207_221751](https://user-images.githubusercontent.com/65513597/101406756-2c2b6700-38da-11eb-87e1-78c5360c47bf.jpg)

**Comment by PabloGirol** [comment]
Same as #119

**Comment by GuiGui73YT** [comment]
> Same as #119 

Yes
I didn't see the other post sorry for my post it is not useless
