### ISSUE TITLE
Modern Warfare

### ISSUE THREAD

**Issue by TheRayJohnson** [Tustin/PlayStationDiscord#129]
Is there anyway to show the correct Modern Warfare? Playing the new 2019 MW (Warzone) shows the old MW.

Apart from that the program works perfectly.

**Comment by albo44** [comment]
They are the same game

**Comment by TheRayJohnson** [comment]
Not really... I'm playing

![Photo](https://upload.wikimedia.org/wikipedia/en/thumb/e/e9/CallofDutyModernWarfare%282019%29.jpg/220px-CallofDutyModernWarfare%282019%29.jpg)

it's showing... (COD 4 MW)
![Photo](https://upload.wikimedia.org/wikipedia/en/5/5f/Call_of_Duty_4_Modern_Warfare.jpg)

Same MW title but different years. I want it to show the new 2019 MW not COD 4 MW, if this is not possible publicly, is it possible local host?

**Comment by albo44** [comment]
oh you should of said the year

**Comment by TheRayJohnson** [comment]
> oh you should of said the year

I thought the 2019 and Old MW covered that but yeah shows the wrong year title lol

**Comment by albo44** [comment]
did you say you where play the warzone part of the game and not the paid version of the full game?

**Comment by TheRayJohnson** [comment]
> did you say you where play the warzone part of the game and not the paid version of the full game?

I play both modes (Warzone) was to avoid confusin with which MW title but yeah i play both MW: MP and Warzone BR.

Play Cold War too but seems it's not supported yet.

**Comment by albo44** [comment]
good hopefully the bug will get fixed.

**Comment by nmcc1212** [comment]
also have the same issue when playing MW 2019 it shows as  MW 4

**Comment by xFGhoul** [comment]
Having the same issue here as well
