### ISSUE TITLE
Doesn't open

### ISSUE THREAD

**Issue by cl3yk** [Tustin/PlayStationDiscord#13]
Program doesn't open. I have not found the solution to the problem in the internet

**Comment by Tustin** [comment]
I'll need more info. What OS are you using? Also check %appdata% for a PlayStationDiscord folder and see if there's anything inside of it. Finally, is it crashing the very first time you opened it? or has it worked before?

**Comment by MOBXS** [comment]
I'm on windows 7 SP1 32-bit with .net framework 4.7 installed application fails to start.

**Comment by Tustin** [comment]
Just release the new version 2.1.0.0. Please try it and let me know if the problem persists.

**Comment by MOBXS** [comment]
Still crashes. Maybe im missing something?

**Comment by MOBXS** [comment]
Ok it works now but the page is blank with script pop up errors when trying to login.

**Comment by Tustin** [comment]
Ah that's my fault I believe. Let me check it real fast and I'll push an update to fix it.

**Comment by Tustin** [comment]
@MOBXS I re-uploaded the setup file for v2.1.0.0 instead of making a new release because it was such a small change. Go ahead and download it from here and let me know if it fixes that problem 😄 https://github.com/Tustin/PlayStationDiscord/releases/tag/2.1.0.0

**Comment by Tustin** [comment]
I'll try to see if I can repro this issue and find a solution. That's why I dropped that version of the web browser to begin with; it just seems to have random issues like this.

**Comment by MOBXS** [comment]
Ok after updating windows past SP1 it seems to have fixed this. Now i can see everything and even sign in.

**Comment by MOBXS** [comment]
It doesn't seem to update status tho.

**Comment by Shikadanako** [comment]
the progam doesn't open. i tried to download several times, but it didn't work...

**Comment by Tustin** [comment]
I just released the newest version of PlayStationDiscord which has been completely rewritten and should fix any previous issues: 
https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.0

Just download `installer-PlayStationDiscord-3.0.0.exe` if you use Windows or `PlayStationDiscord-3.0.0.dmg` if you use Mac!
