### ISSUE TITLE
Alternative for PS3 Rich Presence error message

### ISSUE THREAD

**Issue by xetsubou** [Tustin/PlayStationDiscord#132]
Hello to everyone reading, I've been here a lot recently in hopes to see the PS3 rich presence being fixed but to no avail. Even after hours of searching I couldn't find anything for the longest and I really did not want to learn coding around this to get it to work myself haha. Earlier today I found something while I was searching again and came across **MultiRPC**, google it. It lets you easily create your own rich presence with all the details just the way you want, it may seem alittle confusing at first but the program has a few directions for a better understanding. the cons are that you have to manually turn it on and off, as well as make a profile for each game and you have to add the image for each game if you want an image of said game displayed, the customization is up to you. (Not sponsored by them or anything i'd just like to share this as I would have liked to find it a few months ago lol)
![image](https://user-images.githubusercontent.com/68286491/103265936-c6804700-497c-11eb-953f-01d628b93aee.png)

**Comment by RazzeeX** [comment]
Thanks for the heads up!
