### ISSUE TITLE
Add other game images?

### ISSUE THREAD

**Issue by XGalaxie** [Tustin/PlayStationDiscord#135]
Hello,
I think it would be interesting to add other game images!
For example Genshin Impact, or Fall Guys, Crash Team Racing and many others!

**Comment by TheRayJohnson** [comment]
> You could also manually add a game you want and open a PR on the PlayStationDiscord-Games repo. The PR will be merged depending on if you added the game properly. There's a possibility that this process will be streamlined in the future.

Create a pull in the required format. :)
