### ISSUE TITLE
Add automated tests

### ISSUE THREAD

**Issue by RA80533** [Tustin/PlayStationDiscord#137]
**Is your feature request related to a problem? Please describe.**
Commit c457fc1 fixed an issue with logging in to PSN. Taking a look at the changes, it becomes clear exactly why the issue came about in the first place: there are no automated tests to verify it previously worked.

**Describe the solution you'd like**
Every feature shared between files should have at least one automated test.

**Additional context**
[The documentation for the Jest testing framework](https://jestjs.io/docs/en/getting-started) is a useful starting point.

**Comment by Tustin** [comment]
Not possible. The sole reason why login fails is due to Akamai's bot mitigation software that Sony uses for the login form. Automated tests would trigger that exact problem.

**Comment by RA80533** [comment]
For features such as interacting with an external API, testing need not exist to test genuine flows of execution but rather simulate expected outcomes from such flows of execution. In this case, something that is "not possible" suggests the feature does not work *at all*.

Under what conditions does a genuine login succeed?

Regardless, I should've titled the issue a bit differently to apply specifically to verifying the fix from #77. The general issue of automated tests still applies throughout the repository.
