### ISSUE TITLE
Doesn't happen anything.

### ISSUE THREAD

**Issue by FrankyXD** [Tustin/PlayStationDiscord#14]
Hi, I just downloaded the program and when i click on log in with playstation doesn't happen anything. I don't know what to do. I use Windows 10.

**Comment by dudekd** [comment]
I had same issue on Win10, after last update I also downoaded latest .NET framework, works perfect now. Thanks Tustin

**Comment by Tustin** [comment]
Glad to hear it. Thanks for testing! 👍

**Comment by Rohul1997** [comment]
Still no icon showing btw, playing Spyro

**Comment by TimV01** [comment]
I can't see my second captcha after clicking on "view image"

**Comment by Tustin** [comment]
@TimV01 Out of my control unfortunately. This fallback web browser is the last reasonable option I could add and it's absolutely terrible but at the very least it _should_ somewhat work. I got rid of it before because you get stuck in captcha hell sometimes and it just takes 100 years to login.

**Comment by TimV01** [comment]
@Tustin so you can't implement Chrome as browser?

**Comment by Tustin** [comment]
I could, but Chromium has a lot of overhead that I didn't really want to bundle into the program. Plus when I tried to implement it in C# before, I ran into some issues compiling it. It's always a possibility but if I did, it'd probably be a separate version that should only be used by people who can't get the main thing to work.

**Comment by TimV01** [comment]
Everytime when I did a captcha, it get stuck on this.
https://i.imgur.com/kGcXaRl.png

After that I get this error: https://i.imgur.com/gBdv61n.png

**Comment by Tustin** [comment]
I just released the newest version of PlayStationDiscord which has been completely rewritten and should fix any previous issues: 
https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.0

Just download `installer-PlayStationDiscord-3.0.0.exe` if you use Windows or `PlayStationDiscord-3.0.0.dmg` if you use Mac!
