### ISSUE TITLE
Can't Sign Out, Button Doesn't Work

### ISSUE THREAD

**Issue by TheGhost2** [Tustin/PlayStationDiscord#143]
I logged in to my account without any problems and it's showing which game I'm playing on ps4. I used to sign out without any problems too before but now it just doesn't work. It's asks "Are you sure you want to sign out?" when I click sign out and doesn't do anything when I click "Yes". Closing the app doesn't work either, it just logs back in by itself when I open it next time. I'm using windows 10.

**Comment by Gazza0014** [comment]
still same problem ?
