### ISSUE TITLE
Tutorial linux?

### ISSUE THREAD

**Issue by invidiaanti** [Tustin/PlayStationDiscord#145]
**Is your feature request related to a problem? Please describe.*
No i don't think so but I use linux and the steps to install the application are not clear, i only get to the "cd" part and for the rest can't install it
**Describe the solution you'd like**
A tutorial of the steps
**Additional context**
I've looked for any type of tutorial on youtube but no one seems to use linux so i can't find any

**Comment by xFGhoul** [comment]
If you want to use this on linux you are required to build it manually from source, [read here](https://github.com/Tustin/PlayStationDiscord#developing) for instructions on how to build from source.

**Comment by Tustin** [comment]
Yeah sorry, I included a Snap package file which seems to be a package distro for Linux. I don't use Linux and haven't really even tested that file; I just have the package builder create it automatically.
