### ISSUE TITLE
No longer showing ps3 game status

### ISSUE THREAD

**Issue by Auxy6858** [Tustin/PlayStationDiscord#149]
**Information**
- OS:  Linux ( Debian 10)
- Version: Latest

After the 3.2.0 update it is only able to show ps4 and ps5 status and if you use anything before that you get an error message saying "unable to connect with discord check log for more information"

**Comment by TheFishyGamer11** [comment]
Having the same issue on PS3 with PlayStationDiscord 3.2.0 using Windows 10.
