### ISSUE TITLE
Vita status gets stuck in Standby

### ISSUE THREAD

**Issue by MagicSheep** [Tustin/PlayStationDiscord#15]
While it displays the game properly, after closing the game and putting the Vita in sleep mode, the status stays on Online, then eventually goes to Standby, but gets stuck there. PSN reports my account as being offline so I don't know if I did something wrong or maybe my status is getting detected incorrectly.

Actually, as I was typing this out, the program crashed. Upon restart the status was displaying correctly. I suppose just restarting the program after playing with the vita will get it unstuck from Standby.

I'm not exactly sure what info would be relevant for this but I'm on:
Windows 10, build 1809 (October 2018 Update)
.Net 4.5 and 4.6 installed.

**Comment by Tustin** [comment]
I think I made a change in the new update that might've messed up the handling of the program shutdown and whenever you go offline on the console. I noticed something similar when I was playing the other day. I'll have a look and see if I can figure out what went wrong.

**Comment by MagicSheep** [comment]
Oh cool. Hopefully your search goes well.
Let me know if you need any help testing anything later on though.
