### ISSUE TITLE
Error Logging in 3.2.0

### ISSUE THREAD

**Issue by chancedoescode** [Tustin/PlayStationDiscord#153]
**Information**
- OS: Windows
- Version: Latest

**Describe the bug**
When I try to login on the latest version I am getting 
![image](https://user-images.githubusercontent.com/69983078/111052560-c1974380-8453-11eb-84f3-320e958ab21a.png)

**Comment by PsychoTechGames** [comment]
Can confirm. Password I type in is also correct. Multiple attempts to see if wrong/

**Comment by Deakia** [comment]
I am also Getting this issue

**Comment by impacta-cca** [comment]
same here ;-;

**Comment by lucas-silvs** [comment]
same here ;-;

**Comment by xSousa** [comment]
same, im using an older version and it works.

**Comment by lucas-silvs** [comment]
> same, im using an older version and it works.

Thanks man,  the version 3.0.2 work perfectly

**Comment by ROOTBEEROFF** [comment]
How can I use an older version on Windows ?

**Comment by SpencerFerret** [comment]
Same here
