### ISSUE TITLE
Connection error while signing in

### ISSUE THREAD

**Issue by ChaoticNebula5** [Tustin/PlayStationDiscord#158]
**Information**
- OS: Windows / macOS / Linux (Ubuntu, Debian, etc...)
- Version: Latest

**Describe the bug**

**Log**
Provide the bottom (or all) of your log file for PlayStationDiscord.
- Windows: `%APPDATA%\PlayStationDiscord\log.log`
- macOS: `~/Library/Logs/PlayStationDiscord/log.log`
- Linux: `~/.config/PlayStationDiscord/log.log`
```
[log contents]
```

**Additional context**
I got logged out and when I enter my password it shows the error in the screenshot attached
<img width="394" alt="Screenshot 2021-04-05 at 4 52 56 PM" src="https://user-images.githubusercontent.com/69293452/113569056-6fe77080-962f-11eb-8709-c8110a4edd0a.png">

**Comment by rxxxxxxx** [comment]
![image](https://user-images.githubusercontent.com/82044424/113731047-58bc8780-96f0-11eb-802e-33f703193727.png)
having same issue

**Comment by ChaoticNebula5** [comment]
So I redownloaded both discord and playstation discord, seems to work now

**Comment by rxxxxxxx** [comment]
Uninstalled Discord and playstation discord, installed them again, and I still get the same issue 

![image](https://user-images.githubusercontent.com/82044424/113867535-94b22400-97a6-11eb-83a5-666a088a5b9e.png)
