### ISSUE TITLE
A Connection to Server problem still happening

### ISSUE THREAD

**Issue by rxxxxxxx** [Tustin/PlayStationDiscord#159]
**Information**
- OS: Windows 
- Version: Latest (3.2.0)

**Describe the bug**
When signing into your Playstation account on PlayStation Discord, once you have entered a password (correct or incorrect for the account), an error will appear, stating "A connection to the server could not be established".

![image](https://user-images.githubusercontent.com/82044424/114214882-cf5dbd00-995c-11eb-9a9d-fe230f6b9d6e.png)

**Log**
Provide the bottom (or all) of your log file for PlayStationDiscord.
- Windows: `%APPDATA%\PlayStationDiscord\log.log`

There is no file named "log.log", there is a folder named "logs" with a file called "main" which includes:

[log contents]
[2021-04-09 17:44:38.007] [info] Saved new version of games.json

**Additional context**
Reinstalling Discord and PlayStation Discord does not work, as I own a PS5, I am unable to use previous versions because it does not say I am online when I use a PS5, even when I am playing PS4 game. This is a current issue which has had 2 recent bug reports, and I believe the most recent bug report on this issue was closed incorrectly. I disabled 2 factor authentication on my account, but the problem still occurs. I spoke with PlayStation Live Chat about the issue twice, and they both linked the same webpage to something which does not help. But they stated that the issue is not with the PlayStation account. 

![image](https://user-images.githubusercontent.com/82044424/114220774-53677300-9964-11eb-9a44-d4b697cbc830.png)

**Comment by Tustin** [comment]
As I've said in other issues, this is out of my control. I don't work for Sony and all I do is embed their login form. Their login form is detecting you as a bot for some reason.

**Comment by rxxxxxxx** [comment]
> As I've said in other issues, this is out of my control. I don't work for Sony and all I do is embed their login form. Their login form is detecting you as a bot for some reason.

On previous versions it lets me sign in, I believe it is an error with the login form, as **clicking on these here:**
![sign in](https://user-images.githubusercontent.com/82044424/114245018-7f482000-9987-11eb-9a2e-8c1a037f128b.png)
**Will bring up this:**
![image](https://user-images.githubusercontent.com/82044424/114245086-a30b6600-9987-11eb-9203-897792a01d90.png)
And the error is showing if the password is correct or incorrect :/
