### ISSUE TITLE
Updating from 3.1.2 to latest error

### ISSUE THREAD

**Issue by theoneandonly33** [Tustin/PlayStationDiscord#160]
**Information**
- OS: Windows
- Version: Latest

**Describe the bug**
I was using 3.1.2 this entire time without knowing of a new release! I went to update automatically and this message pops up.
![image](https://user-images.githubusercontent.com/82244012/114249551-d6072700-9992-11eb-8e23-05c679d0c083.png) 
Now when I try to log in it comes up with a connection to the server could not be established.

**Log**
Provide the bottom (or all) of your log file for PlayStationDiscord.
- Windows: `%APPDATA%\PlayStationDiscord\log.log`
cannot find this file
```

**Additional context**
I have read other issue reports and this popup was never mentioned, this may be the issue.

**Comment by cleverkraft** [comment]
Same issue on the OS X version.

**Comment by cleverkraft** [comment]
Now running 3.2.0 and this is resolved.

**Comment by theoneandonly33** [comment]
> Now running 3.2.0 and this is resolved.

What did you do to fix?

**Comment by cleverkraft** [comment]
> > Now running 3.2.0 and this is resolved.
> 
> What did you do to fix?

When I launched it again, it did a self-update and went from 3.1.2 to 3.2.0. Then it worked. Make sure you are running 3.2.0.
