### ISSUE TITLE
Changing "Playing PlayStation 3/4/5/vita"

### ISSUE THREAD

**Issue by theoneandonly33** [Tustin/PlayStationDiscord#161]
I believe that the discord status should not say "playing 'console' " as it makes it unclear to other server members or friends if you are in a game. If you were playing a game, then close it and wait on home screen for 5 mins then open a new game, there will be no change to the status without clicking on the user.

**Describe the solution you'd like**
Change it to say "Playing 'game' and below that, when clicking on it the console name, switching the two.
For example, the status says "Playing Rocket League" instead of saying "Playing PlayStation 3/4/5/vita"

**Additional context**
If it is possible to do manually without a new version, please let me know!

**Comment by BreakingTV** [comment]
I think both is good. I dont see a big diference

**Comment by CodyRWhite** [comment]
This was discussed a bit further in detail as to why this is a bit more complicated that one might think. 

https://github.com/Tustin/PlayStationDiscord/issues/169
