### ISSUE TITLE
Sign in via Browser

### ISSUE THREAD

**Issue by BreakingTV** [Tustin/PlayStationDiscord#162]
**Is your feature request related to a problem? Please describe.**
The most people of here have the problem with sign in.

**Describe the solution you'd like**
I tought about it and maybe you can add that you can sign in via a browser or somthing like that. There you can login and so the problem is not there anymore.

**Comment by MaitreAnonyme** [comment]
Hello,
I cannot link my PSN account to the software. After having put my password it gives me this message (see attachment): "Impossible d'établir la connexion au serveur. (18.8eb67b5c.1618343607.2444412f)"
it works with your previous version (3.1.2) but with the latest (3.2) no ;(
A patch will be available?
Thank you and good evening

![Capture d’écran 2021-04-13 220511](https://user-images.githubusercontent.com/73798211/114614058-589a2a00-9ca4-11eb-9157-69521948a169.png)
