### ISSUE TITLE
Why does COD warzone shows up as COD modern warfare remastered?

### ISSUE THREAD

**Issue by AXGiv** [Tustin/PlayStationDiscord#163]
**Information**
- OS: Windows / macOS / Linux (Ubuntu, Debian, etc...)
- Version: Latest

**Describe the bug**
Call of duty 

**Log**
Provide the bottom (or all) of your log file for PlayStationDiscord.
- Windows: `%APPDATA%\PlayStationDiscord\log.log`
- macOS: `~/Library/Logs/PlayStationDiscord/log.log`
- Linux: `~/.config/PlayStationDiscord/log.log`
```
[log contents]
```

**Additional context**
Why does COD modern warfare/warzone shows up as COD modern warfare remastered?

**Comment by CodyRWhite** [comment]
It looks like the game icons have not been refreshed in a while. The code for that section also pulls down what ever PSN is using for that game at the time. 

I created a pull request to have the icons updated

https://github.com/Tustin/PlayStationDiscord-Games/pull/149
Hoping it will be approved. I see 75 other pull requests waiting for approval
