### ISSUE TITLE
Not able to login 

### ISSUE THREAD

**Issue by GrazePossum** [Tustin/PlayStationDiscord#164]
windows 

im not able to login to the app

it gives me the error 
A connection to the server could not be established. 
(18.90e11602.1618680872.5a18598)

**Comment by HaveANiceDay2** [comment]
i got the same sort of thing where it says:

A connection to the server could not be established.
(18.45fe19b8.1618693834.39bf674)

**Comment by daylightEX** [comment]
I'm having the same issue, but with another error code.

**Comment by daylightEX** [comment]
Nevermind - I have just tried and it has allowed me to log in. I guess this was an issue on Sony's end or something?

**Comment by ExiledEye** [comment]
Same error.

**Comment by Andy7301** [comment]
same error

**Comment by jph168** [comment]
![error](https://user-images.githubusercontent.com/31376624/117339291-6e8aad00-ae54-11eb-8442-b744eea11e4b.png)

> playstationdiscord@3.2.0 start
> npm run compile && cross-env NODE_ENV=dev electron .


> playstationdiscord@3.2.0 compile
> npm run lint && tsc && sass ./assets/app.scss ./dist/app.css --style=compressed --no-source-map


> playstationdiscord@3.2.0 lint
> tslint --project .

10:15:10.992 › PlayStationDiscord-Games has not been updated, using cached version

**Comment by CodyRWhite** [comment]
Please try this update. 
https://github.com/Tustin/PlayStationDiscord/issues/170#issuecomment-872397335
