### ISSUE TITLE
Boot at windows startup.

### ISSUE THREAD

**Issue by ExiledEye** [Tustin/PlayStationDiscord#166]
**Is your feature request related to a problem? Please describe.**
The program works by staying in the background so it makes sense having a option to make the program boot with windows.

**Describe the solution you'd like**
Adding an option so you can choice to let the program on windows boot or not and if minimized or not.

**Comment by Powelus** [comment]
You can actually do this yourself with few easy steps:

Press the Windows logo key + R, type shell:startup, then select OK. This opens the Startup folder.

Copy and paste the shortcut to the  Startup folder.

Next time your PC turns on, it will automatically launch the app
