### ISSUE TITLE
A connection to the server could not be established, fix anyone? 

### ISSUE THREAD

**Issue by GibboGamess** [Tustin/PlayStationDiscord#167]
Does anyone know how to fix this issue? i have a Playstation 5 and would like to show what im playing to discord.

'A Connection to the server could not be established. (18.d8655f.1619090663.6b2e161)' 

Thank you

**Comment by Beatsz** [comment]
Yeah I've been getting the same issue ere as well

**Comment by Beatsz** [comment]
> Does anyone know how to fix this issue? i have a Playstation 5 and would like to show what im playing to discord.
> 
> 'A Connection to the server could not be established. (18.d8655f.1619090663.6b2e161)'
> 
> Thank you

OK so I got it working now apparently version Playstation Discord 3.1.2 seems to be working well. You can just download it from releases section

**Comment by JohnTRL** [comment]
I Managed to stop the Auto-Update. Install version 3.1.2, then go to the app's files, go to "Recources" folder and then, delete the app-update.yml. If u delete this file, then the app, can't find the github repository and then the Auto-Update stops working. xD

**Comment by Beatsz** [comment]
5head dud. Case closed.
