### ISSUE TITLE
Show game name instead of console name

### ISSUE THREAD

**Issue by essmehdi** [Tustin/PlayStationDiscord#169]
**Is your feature request related to a problem? Please describe.**
For me it doesn't make sense to show "Playing **PlayStation 4**".

**Describe the solution you'd like**
Instead I would like to see "Playing **Call of Duty: Modern Warfare**"

It would be also nice if it was a choice rather than a change.

**Comment by wyntrr-end** [comment]
I've been using this program for a while and I completely agree. I came to the GitHub page to see if anyone else had asked about this feature too.

**Comment by DespicableKee** [comment]
> I've been using this program for a while and I completely agree. I came to the GitHub page to see if anyone else had asked about this feature too.

This could be possibly done, but due to how Discord works, this would require a new 'application' for every single game. While this would allow for more extensive customization from the experienced end-user, the average user would have no idea about Discord applications, nor why the PlayStationDiscord-Games repository would have to have a completely different format. The current api is supposed to add title ids to the application, but that cannot be done when new applications need to be created for each game. I would love this as an option, but this shouldn't be the normal way it is displayed.

**Comment by DespicableKee** [comment]
> > I've been using this program for a while and I completely agree. I came to the GitHub page to see if anyone else had asked about this feature too.
> 
> This could be possibly done, but due to how Discord works, this would require a new 'application' for every single game. While this would allow for more extensive customization from the experienced end-user, the average user would have no idea about Discord applications, nor why the PlayStationDiscord-Games repository would have to have a completely different format. The current api is supposed to add title ids to the application, but that cannot be done when new applications need to be created for each game. I would love this as an option, but this shouldn't be the normal way it is displayed.

If you don't believe this, take a look into the applications code. You'll see it changes application ID based on console, and thus the console name is changed. If you load that application id through any external rich presence client, it'll indeed show the console name with the id associated with it.

**Comment by CodyRWhite** [comment]
I investigated this issue a bit further... Its not that is impossible, it all just depends on the game as well. Some game developers already have applications created in discord for their PC version of the games. There is a possibility of utilizing those application ID's to then send the data to discord using that developers application ID. We would be limited on what we could do but it could work. 

Then when we come across a game that does not have "native" support we could wrap the default application as it is now. 

I don't believe that change is necessarily hard to do, there is just no way to dynamically do it. Each game would have to be hard coded or have a unique ts file and a new build would have to be released for each update. 

The hardest part would be getting the Application ID's for PC equivalent versions of the game.
