### ISSUE TITLE
Add thumbnails for more games like Watch Dogs 2, The crew 2, Genshin Impact etc.

### ISSUE THREAD

**Issue by ChaoticNebula5** [Tustin/PlayStationDiscord#176]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by d-rez** [comment]
@ChaoticNebula5 you can contribute and add more games by creating a pull request at https://github.com/Tustin/PlayStationDiscord-Games

Though it looks abandoned :(

**Comment by Jopo-JP** [comment]
No need for it anymore. Discord now allows external sources for the display icon. The software just insert the url of the given PS4 or PS5 game and thats it. We don't need to upload all files manually anymore.
