### ISSUE TITLE
Playstation Authentication Error: A Connection to the Server could not be established

### ISSUE THREAD

**Issue by vvirtues** [Tustin/PlayStationDiscord#179]
**Information**
- OS: Windows
- Version: 3.2.0 (latest)

**Describe the bug**
When signing in to PlayStation right after opening the app, it allows me to enter any username and password, but then shows this
![image](https://user-images.githubusercontent.com/81705406/124653053-d6686e80-de6a-11eb-8874-12e5305c2624.png)

**Log**
I gave you everything. It's quite short
```
[2021-07-06 14:39:43.515] [info] Saved new version of games.json
[2021-07-06 14:42:58.779] [info] PlayStationDiscord-Games has not been updated, using cached version
[2021-07-06 14:50:52.654] [info] PlayStationDiscord-Games has not been updated, using cached version
```

**Additional context**
Pretty much disable the use completely

**Comment by Raphfriend** [comment]
I can confirm.

**Comment by voidel** [comment]
Also getting this.

**Comment by Sarentheturian** [comment]
Does anyone have a fix for this on Mac Os?

**Comment by Rigari** [comment]
Does anyone have a fix for this on macOs?

**Comment by PowerHydra** [comment]
![image](https://user-images.githubusercontent.com/70647981/125999497-2af75190-03c3-44e6-886c-c12543d1631c.png)

**Comment by AhmedAlEryani** [comment]
same: 
![image](https://user-images.githubusercontent.com/17525965/126080033-1aa3307f-63f4-4899-9b05-0eb6c6c77d52.png)

**Comment by GhostSlayer** [comment]
![image](https://user-images.githubusercontent.com/51095261/126219407-18c0fc93-00df-4924-8fcf-64f36f8bde3e.png)

**Comment by Faiyaz-E** [comment]
> Also getting this.
> 
> Edit: The resolution here fixed it for me
> [#170 (comment)](https://github.com/Tustin/PlayStationDiscord/issues/170#issuecomment-872397335)

could you please explain how you fixed it cuz the comment made no sense to me. I did not understand how to fix the problem :(

**Comment by Velv5225** [comment]
I turned off my adblocker for github and it worked

**Comment by TheOnlyMason** [comment]
It still wont work for me. I can login but it crashes when trying to enable online

**Comment by hikari0202** [comment]
There's some problem with Captcha, it's required to login to PSN but for some reason it doesn't pop-up however.

**Comment by theDragoon008** [comment]
3.2.0-1 (3.2.1 ig?) fix for those who dont know how to made by the guy who gave the solution 
https://github.com/vivitchka/PlayStationDiscord/releases/tag/v3.2.0-1

**Comment by theDragoon008** [comment]
> > Also getting this.
> > Edit: The resolution here fixed it for me
> > [#170 (comment)](https://github.com/Tustin/PlayStationDiscord/issues/170#issuecomment-872397335)
> 
> could you please explain how you fixed it cuz the comment made no sense to me. I did not understand how to fix the problem :(

^
