### ISSUE TITLE
Says Offilne but not offline :/ 

### ISSUE THREAD

**Issue by PanZaZ** [Tustin/PlayStationDiscord#185]
**Information**
- OS: Windows 10
- Version: 3.2.0 cuz newer ones never let me log in. 

**Describe the bug**
Online but says I'm not on app. just stays on offline but I'm on a game on my ps4 

[log contents]
[2021-08-03 17:06:51.485] [info]  Stopped rich presence loop
[2021-08-03 17:06:51.486] [info]  Status set to online
[2021-08-03 17:06:51.516] [error] Failed updating rich presence Discord controller not ready
[2021-08-03 17:07:16.350] [info]  PlayStationDiscord-Games has not been updated, using cached version
[2021-08-03 17:07:18.910] [info]  Running refreshAuthTokensLoop
[2021-08-03 17:07:18.919] [info]  Saved oauth tokens

**Additional context**
 the newer ones don't let me log in.

**Comment by ExiledEye** [comment]
3.2.0 is the latest.
Are you using 3.2.0-1 by boozerboozeman?

**Comment by AliCreed** [comment]
Same issue here... I am using 3.2.0-1 by boozerboozeman.

**Comment by AliCreed** [comment]
I figured out how to solve this. What I did is log into PSN via 3.2.0-1 by boozerboozeman then delete PlaystationDiscord. I then downloaded 3.2.0 from here: https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.2.0

I was still logged in and online.

**Comment by lividhen** [comment]
> 
> 
> I figured out how to solve this. What I did is log into PSN via 3.2.0-1 by boozerboozeman then delete PlaystationDiscord. I then downloaded 3.2.0 from here: https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.2.0
> 
> I was still logged in and online.

This worked for me too!

**Comment by LumineAstreia** [comment]
> 
> 
> I figured out how to solve this. What I did is log into PSN via 3.2.0-1 by boozerboozeman then delete PlaystationDiscord. I then downloaded 3.2.0 from here: https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.2.0
> 
> I was still logged in and online.

You're a lifesaver. Thank you!

**Comment by YoXpertguyZ** [comment]
where can i find the boozerman file?

**Comment by SamPurples** [comment]
> 

ty bro !!
You're my lifesaver too !
