### ISSUE TITLE
Windows Smartscreen + Unknown Publisher

### ISSUE THREAD

**Issue by KryskZ09** [Tustin/PlayStationDiscord#19]
Windows 8.1 doesn't open the install app unless ran in administrator and given access. Windows SmartScreen detects it as an unknown application. Then after agreeing to run the app, the publisher is also unknown.

Also after installing, the app will not open (even when ran in administrator)

**Comment by Tustin** [comment]
Unfortunately not much I can do unless I purchase a code signing certificate for both Windows and Mac which is a bit ridiculous considering it's an open source project. For now, you'll just have to ignore the warning.
