### ISSUE TITLE
How to use the PlayStationDiscord with Linux

### ISSUE THREAD

**Issue by twjnk** [Tustin/PlayStationDiscord#193]
I recently got a Chromebook and I've learned how to use Linux and what not but I do not know how to run PlayStationDiscord? I installed the Linux version and everything. If somebody could help me figure out how to use it, that would be great.

**Comment by akr13** [comment]
I was able to install it using Ubuntu following the instructions listed under the "Developing" section. I've copy-pasted the instructions below, hope it helps!

```

1. git clone https://github.com/Tustin/PlayStationDiscord/
2. cd into PlayStationDiscord folder
3. npm install (or yarn install)
4. npm run start (or yarn start)

```

You may need to need to install git and npm before you use those commands (`sudo apt install npm` and `sudo apt install git`).
