### ISSUE TITLE
[Question] Is this project being maintained?

### ISSUE THREAD

**Issue by xFGhoul** [Tustin/PlayStationDiscord#196]
Pull requests are not being merged or reviewed, issues are not being responded too, a commit was last seen months ago, is this dead? or are you just really busy, @Tustin

**Comment by joshlopes** [comment]
Pull requests are from a bot -- they are not critical. Tustin did work on this 5 months ago -- it's not dead but is not active either.

**Comment by xFGhoul** [comment]
When I say pull requests are not being merged or reviewed, I'm referring too [PlaystationDiscord-Games](https://github.com/Tustin/PlayStationDiscord-Games) which goes hand in hand with this repository
