### ISSUE TITLE
You,ll need a new app to open com.playstation.playstationapp link fix

### ISSUE THREAD

**Issue by Rudra2022** [Tustin/PlayStationDiscord#197]
**Information**
- OS: Windows / macOS / Linux (Ubuntu, Debian, etc...)
- Version: Latest

**Describe the bug**It is showing You,ll need a new app to open com.playstation.playstationapp link please check in microsoft store

**Log**
Provide the bottom (or all) of your log file for PlayStationDiscord.
- Windows: `%APPDATA%\PlayStationDiscord\log.log`
- macOS: `~/Library/Logs/PlayStationDiscord/log.log`
- Linux: `~/.config/PlayStationDiscord/log.log`
```
[log contents]2021-11-27 14:21:11.546] [info] Saved new version of games.json
[2021-11-27 14:34:33.939] [info] PlayStationDiscord-Games has not been updated, using cached version
```

**Additional contextI dont know what is hapenning im online in my account but still its showing offline please help me in this issue

**Comment by daazayy3ee** [comment]
currently, I'm having the same issue

**Comment by guiathayde** [comment]
currently, I'm having the same issue
