### ISSUE TITLE
I mighta found a workaround???

### ISSUE THREAD

**Issue by Zaccian** [Tustin/PlayStationDiscord#198]
I backdated to the 3.0.2 version, copied those files, but I didn't use them because I logged in on the 3.2.0 version and it worked??? lowkey confused, here's the process, install 3.0.2 > login > wait 10 seconds > close app > install 3.2.0 > launch and login, and it might work? idk man

**Comment by SOEBREN** [comment]
I tried that, didn't work for me sadly, maybe because i have 2fa enabled? i dont entirely know...

**Comment by Zaccian** [comment]
> I tried that, didn't work for me sadly, maybe because i have 2fa enabled? i dont entirely know...
you might be able to login if you sign in on 3.0.2, copy those files to a directory on ur desktop like 'Desktop/backup" upgrade to 3.2.0, and replace the new files with the old

**Comment by kiehnle** [comment]
Here's my workaround. I downloaded the patch from https://github.com/inthecatsdreams/PlayStationDiscord/releases/tag/v3.2.0-1. Then reinstalled 3.2.0. I was still signed on after the update.

**Comment by Zaccian** [comment]
> Here's my workaround. I downloaded the patch from https://github.com/inthecatsdreams/PlayStationDiscord/releases/tag/v3.2.0-1. Then reinstalled 3.2.0. I was still signed on after the update.

Noice.
