### ISSUE TITLE
Doesn't update my status in Discord.

### ISSUE THREAD

**Issue by ItMeBayside** [Tustin/PlayStationDiscord#2]
I get signed in and everything but it doesn't actually update my status on Discord. I try playing a game on my PS4 and it doesn't update there either.

**Comment by Tustin** [comment]
Dumb question but, are you running the Discord application and not the web version? Rich Presence won't work if you're using the web version of Discord.

**Comment by ItMeBayside** [comment]
No, definitely running the application.

**Comment by Tustin** [comment]
Well also make sure that you have the option enabled to show which game your playing. Other than that, I really don't have any idea why it wouldn't work. Hasn't happened to anyone else who has used it so unless you can debug the program yourself I'm not sure how to repro it.
