### ISSUE TITLE
Program doesn't open

### ISSUE THREAD

**Issue by Shikadanako** [Tustin/PlayStationDiscord#20]
i installed the program, but when i tried to open, it didn't.

i think its because my pc is 64 bits...

**Comment by Jinxyface** [comment]
Same. Program installs fine, but upon launching and clicking "Sign in with Playstation", the program just hangs until I force quit it with Task Manager. Version 2.1.0.0 on Windows 10 x64 1809

**Comment by Shikadanako** [comment]
in your case, the program at least opens, i keep clicking and the program doesn't open at all.

Version 2.1.0.0 on windows 10 pro x64.

**Comment by baxenko** [comment]
+1 Windows Server 2016, pogram doesn't run :-(

**Comment by Tustin** [comment]
I just released the newest version of PlayStationDiscord which has been completely rewritten and should fix any previous issues: 
https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.0

Just download `installer-PlayStationDiscord-3.0.0.exe` if you use Windows or `PlayStationDiscord-3.0.0.dmg` if you use Mac!
