### ISSUE TITLE
it says offline when im online

### ISSUE THREAD

**Issue by madridplayz** [Tustin/PlayStationDiscord#200]
**Information**
- OS: Windows / macOS / Linux (Ubuntu, Debian, etc...)
- Version: Latest

**Describe the bug**
A clear and concise description of what the bug is. it says im offline and i was playing fifa and still no work

**Log**
Provide the bottom (or all) of your log file for PlayStationDiscord.
- Windows: `%APPDATA%\PlayStationDiscord\log.log`
- macOS: `~/Library/Logs/PlayStationDiscord/log.log`
- Linux: `~/.config/PlayStationDiscord/log.log`
```
[log contents]
```

**Additional context**

**Comment by guiathayde** [comment]
Try to download this version with the login fixed [here](https://github.com/inthecatsdreams/PlayStationDiscord/releases/tag/v3.2.0-1), and then install the normal version of Tustin.
