### ISSUE TITLE
A connection to the server could not be established

### ISSUE THREAD

**Issue by sudoShiba** [Tustin/PlayStationDiscord#208]
**Information**
- OS: macOS
- Version: Latest

**Describe the bug**
Error: `A connection to the server could not be established`

**Log**
I only had `main.log`
```
[2022-01-02 14:50:19.090] [info] Saved new version of games.json
```
**Additional context**
I have 2FA turned on

**Comment by diegolamanno** [comment]
I believe this is a clone from #199

**Comment by sudoShiba** [comment]
yeah but this is with macos

**Comment by diegolamanno** [comment]
@shibaismyname read my comment in the other thread! I don't think it is an OS related situation.

**Comment by sudoShiba** [comment]
now it works lol I didn't change anything just waited a day, but ig this is a clone from #199
