### ISSUE TITLE
Mac version?

### ISSUE THREAD

**Issue by NPCtom** [Tustin/PlayStationDiscord#21]

**Comment by NPCtom** [comment]
Could you create a mac version of the application? would be very helpful!

**Comment by Tustin** [comment]
New version in the works right now will be cross platform! 🍾

**Comment by LLIYTHUK** [comment]
> New version in the works right now will be cross platform! 🍾

Hello, i'm with my friend Teriand adopted mac version Ps4Rpc to non english languages and now we have game pictures ^^) also online status show number of  platinum when not in game.

![2019-02-16 3 12 35](https://user-images.githubusercontent.com/4716953/52891052-61147a00-3199-11e9-9c49-6428a198db28.png)
![2019-02-16 3 17 08](https://user-images.githubusercontent.com/4716953/52891054-6376d400-3199-11e9-900f-03b284047e2b.png)


Check it please https://github.com/Teriand/Ps4Rpc

**Comment by Tustin** [comment]
I just released the newest version of PlayStationDiscord which has been completely rewritten and should fix any previous issues: 
https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.0

Just download `installer-PlayStationDiscord-3.0.0.exe` if you use Windows or `PlayStationDiscord-3.0.0.dmg` if you use Mac!
