### ISSUE TITLE
Offline issue for PlayStation 3

### ISSUE THREAD

**Issue by Devfye** [Tustin/PlayStationDiscord#210]
Hello I'm having an issue to show my status for discord for my PS3. It shows I'm online when I'm on PS3 but on discord PlayStation it says I'm offline when I'm not. Also when I play a game nothing shows up on discord either because discord PlayStation shows me offline when I'm not. Is there a way to fix this?

**Comment by Fenveros** [comment]
same here, tried a few things from other issues but nothing.

**Comment by Nenkai** [comment]
Downgrading to 3.1.2 fixes the issue here.
https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.1.2
