### ISSUE TITLE
Program closes after certain time

### ISSUE THREAD

**Issue by Firebrand90** [Tustin/PlayStationDiscord#23]
OS: Windows 10 64 -bit
Playing on: PS3 - Metal Gear Rising: Revengence
UAC: Disabled

The program working okay for me, logs in, recognizes game, it's perfect. However after 10-15 minutes it closes. I suspect it crashes because the mini icon on my taskbar still there and only disappears if I hover my mouse over it. No error message is left.

**Comment by mostlyash** [comment]
Could you provide your _log.txt_  found in the program startup folder. As this would let us see what's happening.

**Comment by Firebrand90** [comment]
![capture](https://user-images.githubusercontent.com/34612481/52527606-f8765a80-2ccb-11e9-96ce-6dbbbd212e11.PNG)

I think there's no log.txt. Is there any way to enable it?

**Comment by Tustin** [comment]
I just released the newest version of PlayStationDiscord which has been completely rewritten and should fix any previous issues: 
https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.0

Just download `installer-PlayStationDiscord-3.0.0.exe` if you use Windows or `PlayStationDiscord-3.0.0.dmg` if you use Mac!
