### ISSUE TITLE
MAC VERSION Cannot copy and paste

### ISSUE THREAD

**Issue by NPCtom** [Tustin/PlayStationDiscord#26]
Minor error can't copy and paste password/email into the sign in dialog

**Comment by Tustin** [comment]
Very strange, I'll definitely take a look at this. Thanks for letting me know!

**Comment by Tustin** [comment]
This still needs testing. Going to pull it in on my macOS VM and see if it solves the issues.

**Comment by Tustin** [comment]
Seems to be working. I'll have the next update out soon and this will be included. Thanks again for the report. 👍
