### ISSUE TITLE
Displaying ps4 while playing ps3

### ISSUE THREAD

**Issue by bogdinsr** [Tustin/PlayStationDiscord#28]
I play a game on the PS3 but it shows a play said game on PS4

EDIT: A screenshot of me playing Far Cry 2 on PS3. [https://i.imgur.com/Gx2z8vF.png](https://i.imgur.com/Gx2z8vF.png)

**Comment by Tustin** [comment]
I completely forgot to mention that I haven't added support for PS3 and Vita in the new version yet. I will get this added in the next update :)

**Comment by bogdinsr** [comment]
I see. Thank you for the updates.
