### ISSUE TITLE
login problems

### ISSUE THREAD

**Issue by qeqqwqwusqiqwqwqriqoque** [Tustin/PlayStationDiscord#3]
when i try to login i see this
![image](https://user-images.githubusercontent.com/38502068/42127550-b220d2b6-7c92-11e8-9123-6ad83a994bf6.png)

**Comment by Tustin** [comment]
Probably the same issue as this: https://github.com/Tustin/PlayStationDiscord/issues/1#issuecomment-400762323. Try following the steps I posted there and see if it works

**Comment by Tustin** [comment]
I just released the newest version of PlayStationDiscord which has been completely rewritten and should fix any previous issues: 
https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.0

Just download `installer-PlayStationDiscord-3.0.0.exe` if you use Windows or `PlayStationDiscord-3.0.0.dmg` if you use Mac!
