### ISSUE TITLE
Error could not connect 

### ISSUE THREAD

**Issue by dredknot** [Tustin/PlayStationDiscord#31]
Probably not major but throws errors if you start the program without Discord running. Reporting it, since this didn't happen before the recent update.
![psdiscoerror](https://user-images.githubusercontent.com/47759774/52976850-1b260480-3399-11e9-9871-6fad3e65d629.png)

**Comment by Tustin** [comment]
I added messages like this just in case there were issues communicating with Discord RPC. I'd rather throw an error message like this so people know right away when something won't work right. However I am going to add a reconnect button on the form so you don't have to restart the application if you forgot to open Discord beforehand.

**Comment by dredknot** [comment]
Makes sense, I thought it might be something like that. I noticed that behavior before (not always working when started before Discord) because I had PlaystationDiscord start on boot up. The app is sometimes ready before Discord is though, so I just started opening it manually again.

**Comment by Tustin** [comment]
Oh okay, good point actually. I can definitely see about adding additional checks before it throws that message 👍

**Comment by Tustin** [comment]
Actually now that I think of it, in the newest version (3.0.1), I made it so it doesn't initialize the Discord RPC stuff until you're online on PlayStation. So it shouldn't throw that error if you have it start on launch (as long as you're not on PSN).

**Comment by Chris54300** [comment]
I keep getting this error, even after re-connecting and re-opening Discord. Any fix?
