### ISSUE TITLE
Playstation 3 picked up as 4

### ISSUE THREAD

**Issue by Firebrand90** [Tustin/PlayStationDiscord#33]
It appears the latest build showing my PS3 as a PS4 on Discord.

Tried with PSN shop and Dead Space but both displaying as "playing Playstation 4" and game title.

Version: Latest
Windows: 10 x64

I can provide proof if required.

**Comment by deejbruce** [comment]
Support for other PlayStation consoles is in the `development` branch and these changes will be in the next update.

**Comment by Tustin** [comment]
New version has been released and this should be resolved. Please re-open this issue if it doesn't work right. 👍
