### ISSUE TITLE
No image showing on discord

### ISSUE THREAD

**Issue by IChainosI** [Tustin/PlayStationDiscord#34]
![discordpsissue](https://user-images.githubusercontent.com/35256039/53052412-f3b95f80-349e-11e9-8f3d-5c838eb2154a.PNG)
There is no image showing of the game im playing, only text, i have the 3.0.0 version installed. It worked of the version before this but now there is no image

**Comment by Tustin** [comment]
Yep this is a bug I noticed the other night and I fixed it with d17b51c5646b209ac0607f64509049a18a5443f4. I'll have the update out soon. Sorry about that.

**Comment by dolivo** [comment]
Do you now have an increased image pool or is it still limited?

**Comment by Tustin** [comment]
@dolivo Still limited to 150.

@IChainosI New version has been pushed that should fix this issue. If not, please re-open and let me know 👍
