### ISSUE TITLE
Program keeps reverting and trying to update again every time I restart?

### ISSUE THREAD

**Issue by askhavok** [Tustin/PlayStationDiscord#37]
The file still says 3.0.17 but every time i restart it goes back to old UI and then gives the update box...

**Comment by Tustin** [comment]
Are you talking about the original version of the program? It should update properly but if not, just download the latest version here: https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.1 (download `installer-PlayStationDiscord-3.0.1.exe` for Windows). That will try to uninstall the old version but depending on where you installed it to originally, you might have to manually do it.

**Comment by askhavok** [comment]
It does update properly, however it reverts upon restarting the computer. I do not believe it reverts to the original version, just the version pre-rewrite.
