### ISSUE TITLE
port to Electron in Mac

### ISSUE THREAD

**Issue by Frankity** [Tustin/PlayStationDiscord#4]
hi, i'm actually trying to port your app in Electron to mac, but i'm stuck here :( with this api response

this is my code 
![image](https://user-images.githubusercontent.com/1179431/45466980-d2c83380-b6e2-11e8-9106-68e0ce418eac.png)

```
Status: 400
Headers: {"server":"nginx/1.13.10","content-type":"application/json;charset=UTF-8","x-requestid":"a34c879fbf8ec502bf90738998503ef9","x-correlationid":"f5a95542-831e-4620-ad0d-3ea9c14c69dd","x-content-type-options":"nosniff","x-wily-info":"Clear guid=D12162E20AF292FD5284329812DDD690","x-wily-servlet":"Encrypt1 hR/KG2GOR16aRfvv3/q1AZSLdayXltRsNgwZ0cFcndH+enaUbd5rMqaFFoIXqPOXns4UwF3EgzE6uu4CApI8sOk5Vhj2QkGzbXZTD3ZGhaxZPptxzbzIkY01yVc9/zbIbbpigwm5+Ec12rGMIDk96emuO6MNIu9gsDwGzBD+7a+SngMdjv9goWPKZ5Vk4SC5QVuURoOIIqwyNutO3JOc/w==","cache-control":"no-store","pragma":"no-cache","content-length":"156","date":"Thu, 13 Sep 201804:12:30 GMT","connection":"close"}
Body: {"error":"redirect_uri_mismatch","error_description":"Redirect URI mismatch","docs":"https://auth.api.sonyentertainmentnetwork.com/docs/","error_code":4174}
```

any idea about how to continue.

thanks.

Update: i fixed it by removing the `&` from the redirect url.

**Comment by Tustin** [comment]
Apologies -- just saw this. Glad to hear you got it fixed. IIRC, I had to do some hacky method of sending that request because I was also getting issues with the redirect uri being encoded when it wasn't supposed to be.
