### ISSUE TITLE
game icons

### ISSUE THREAD

**Issue by zerveaux** [Tustin/PlayStationDiscord#42]
game icons don't show up 
![image](https://user-images.githubusercontent.com/47952221/54078291-1966a700-429c-11e9-91cf-908a85639580.png)

**Comment by Mr-ttaM** [comment]
@zerveaux
![image](https://user-images.githubusercontent.com/5974123/54675339-3edc9600-4b63-11e9-8367-deff35cef0ca.png)
I'm seeing an image okay for the game I'm playing. Only games showing in [this list](https://raw.githubusercontent.com/Tustin/PlayStationDiscord-Games/master/games.json) will show icons - see the [readme](https://github.com/Tustin/PlayStationDiscord/blob/master/README.md#supported-games) for more info on this

The maintainer will be able to advise better, but I think you can probably add in `{"name": "Tom Clancy's Rainbow Six Siege*", "titleId": "CUSA01800_00**"}` and it _should_ start showing an image for this game.

* Copy this exactly as it shows in the PlayStationDiscord window to make sure it maps properly
** Copy this exactly as it appears in the url of the US store page (from CUSA to _00) for whatever edition of the game it is - I'm seeing gold, deluxe, and ultimate editions and I don't know if the Sony API will report which edition you are using

@Tustin - do you need any help growing the supported games list? Add a how-to to the readme and I can help out at some point for the games I notice are missing and I'm sure others will follow suit

**Comment by ayberk212** [comment]
You can find the list of games in the link below and add some game icons to the project if you want.
https://github.com/Tustin/PlayStationDiscord-Games
