### ISSUE TITLE
[Suggestion] Create a background application macOS

### ISSUE THREAD

**Issue by NPCtom** [Tustin/PlayStationDiscord#44]
Is there anyway to create a background application that doesn't display in the dock? Maybe an addon in the menu bar :)

**Comment by Tustin** [comment]
Unfortunately I don't have a Mac to test with other than a VM and it's a pretty big pain to debug/test stuff on; especially since I'm not too knowledgeable with Electron and cross platform. If you are capable of implementing it then I would pull in the PR 😄

**Comment by roxaloxa** [comment]
Yo @Tustin, I don't mind taking care of this along with #41 . I can submit a pull request soon for it (already got the other one fixed locally).
