### ISSUE TITLE
Swap presence information suggestion

### ISSUE THREAD

**Issue by galenbrazell** [Tustin/PlayStationDiscord#45]
Is it possible to have the rich presence  information swapped? It would be great if there was an option to show “Playing nameofgame” and then the specifics of it being on PS4 and time lapsed are on the click/profile. Is the current setup displaying “Playing PlayStation 4” due to a limitation, or preference?

**Comment by ImHiiro** [comment]
You mean this?
![Screenshot_2](https://user-images.githubusercontent.com/40962597/56395476-ace3ae00-6232-11e9-8631-f0cb2560fdee.png)
![Screenshot_1](https://user-images.githubusercontent.com/40962597/56395478-af460800-6232-11e9-991e-666c61073e3f.png)

**Comment by galenbrazell** [comment]
That's how it currently is. I'm wondering if it's possible to switch it so it shows in the members column on the right the game I'm playing, instead of Playing Playstation 4. I edited with chrome tools to show what I'd like it to say:

![image](https://user-images.githubusercontent.com/3221476/56395848-22c72580-61f1-11e9-83c4-262901328abd.png)

But here is how it normally looks: 

![image](https://user-images.githubusercontent.com/3221476/56395921-70dc2900-61f1-11e9-9eb6-c9b05e85c3b2.png)

**Comment by roxaloxa** [comment]
Seconding this. Wonderful app but came here to suggest this very thing.

**Comment by Tustin** [comment]
Unfortunately this isn't possible. The name that it shows under your name (_Playing PlayStation 4_) is actually the name of the application that is registered in the Discord application settings. Having the actual game name there would require a separate application for each of the games and that's very impractical.

Now if you really wanted to, you could visit the Discord application page [HERE](https://discordapp.com/developers/applications/) and make your own application that uses the name of the game you want to show up and then copy the client ID for the app, fork this repo and change the client ID for my PS4 application to your custom game application [HERE](https://github.com/Tustin/PlayStationDiscord/blob/master/src/Consoles/PlayStation4.ts#L7). You might need to change a few more things in the code for it to work 100% correctly but I think this should be fine.

Hopefully at some point Discord makes something like this possible but for now, I'll close this. Feel free to comment here if you have any questions regarding the custom method I posted above 😄 .

**Comment by roxaloxa** [comment]
Ah, got it. I've tooled around before with Discord statuses but didn't realize that was a limitation of rich presences.

There's actually an official feature request for this functionality on their new SDK (since the RPC one is deprecated now apparently) located here: https://support-dev.discordapp.com/hc/en-us/community/posts/360043629592-Dynamically-set-application-name
