### ISSUE TITLE
God of War 2018 icon missing

### ISSUE THREAD

**Issue by thatJARED** [Tustin/PlayStationDiscord#48]
The icon for when God of War is being played is not functional.

I suggest this icon.
![2603889_0](https://user-images.githubusercontent.com/17349406/57204220-9cd11a00-6ff9-11e9-933d-8834cf75049a.jpg)

**Comment by Tustin** [comment]
It should be showing since it's on the list here: https://github.com/Tustin/PlayStationDiscord-Games.

Although it may be a bug with different regions. I was having issues with it in the past and I'm not sure if I fully fixed it.

**Comment by roxaloxa** [comment]
Looks like God of War 2018 has a ton of different Title IDs based on region and who knows what else.

From https://ps4database.io :
![image](https://user-images.githubusercontent.com/556484/58673943-fb877a80-8390-11e9-9225-068fe6e843f2.png)
