### ISSUE TITLE
Vita Support

### ISSUE THREAD

**Issue by deejbruce** [Tustin/PlayStationDiscord#5]
Is it possible to add Playstation Vita support? Since it can detect what game I play but it says I'm playing on PS4 which is kinda annoying.

**Comment by Tustin** [comment]
Yeah I actually kinda support it, I just don't have it setup on the Discord website yet. I'll do an update for that soon.

**Comment by deejbruce** [comment]
Alright thanks, Everything else works fine!

**Comment by Tustin** [comment]
Started pushing my refactor code, which includes Vita support in it but it needs testing. 347ca6da9f18376f0f9fd1db828bb31b3af41db0

**Comment by Tustin** [comment]
Added Vita support in 2.0, but I'll need someone to test it:
https://github.com/Tustin/PlayStationDiscord/releases/tag/2.0.0.0

**Comment by deejbruce** [comment]
Yeah that's the issue I'm having despite updated. Only tried it with persona 4 so far.

**Comment by Tustin** [comment]
@alec2dabreen  @deejbruce 
Okay, I pushed a new update which added a logfile that will help me figure out what I'm missing. If you download the new update, make sure you're online on the Vita and then launch the program. Go to `%appdata%\PlayStationDiscord\` and open log.txt. You should see a line that looks like this:
```
[2:18:31 PM] - Game = {"onlineStatus":"online","platform":"PS3","npTitleId":"NPUB30638_00","titleName":"Red Dead Redemption","npTitleIconUrl":null,"gameStatus":null,"hasBroadcastData":false}
```

If one of you could post that here, that would help a bunch.

**Comment by alec2dabreen** [comment]
[3:30:25 PM] - Game = {"onlineStatus":"online","platform":"PSVITA","npTitleId":"PCSE00283_00","titleName":"FINAL FANTASY X-2 HD Remaster","npTitleIconUrl":"http://tmdb.np.dl.playstation.net/psp2-tmdb/PCSE00283_00_B33A4ED8CAACE9FA151062C78BF8021737E99538/icon0.png","gameStatus":null,"hasBroadcastData":false}

**Comment by Tustin** [comment]
`"platform":"PSVITA"` Goddamn, there was my problem lol. Sony is so inconsistent with their naming. I'll go ahead and get that fixed and then just update the setup for 2.0.0.1 with proper Vita support. Thanks a bunch @alec2dabreen!

**Comment by Tustin** [comment]
I updated the setup for 2.0.0.1: https://github.com/Tustin/PlayStationDiscord/releases/tag/2.0.0.1. Feel free to try it again and hopefully it properly works now.

**Comment by alec2dabreen** [comment]
Works perfect now! Thank you so much!

**Comment by Tustin** [comment]
Glad to hear. Thanks again for the help. I'll start adding images of some of the most popular Vita games so it'll show the game image instead of the basic PlayStation logo. 😄

**Comment by deejbruce** [comment]
Yeah working just fine now, Thanks again!
