### ISSUE TITLE
New Update Available

### ISSUE THREAD

**Issue by Wildblood82** [Tustin/PlayStationDiscord#54]
App claims there's an update available, but link redirects to v.3.0.0
Running Playstation Discord v3.0.0
MacOS Mojave 10.14.5

**Comment by Tustin** [comment]
Yeah I need to update the link manually on the website. Try downloading the latest version for Mac [here](https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.2) and see if that fixes the problem.

**Comment by Wildblood82** [comment]
Yeah, new version works great, thanks!
