### ISSUE TITLE
List of domains the app connects to -> Firewall rules

### ISSUE THREAD

**Issue by cryptochrome** [Tustin/PlayStationDiscord#60]
Hi,

I am trying to get this app running from behind a sophisticated, enterprise-grade firewall that does SSL decryption (man in the middle). Could you provide a list of all top level domains the app is connecting to so I can put them on a whitelist on the firewall?

Thank you

**Comment by Tustin** [comment]
Sorry for the delay but if you're still interested:
- https://id.sonyentertainmentnetwork.com (login flow)
- https://remoteplay.dl.playstation.net (login flow)
- https://github.com/ (for auto-updating)

It also communicates with Discord (obviously) but I'm pretty sure that's done via RPC and not websockets or anything so there shouldn't be an issue there.
