### ISSUE TITLE
Command line or text based config support

### ISSUE THREAD

**Issue by HoshiYamazaki** [Tustin/PlayStationDiscord#61]
Hey, so not everyone uses Windows or macOS, or maybe some persons wants to run this app on Linux VPS/raspberry pi to have it working always without high electricity cost.

I was reading README.md and there no mention about text or command line config, I'm away from home now so I cant test if this feature is implemented. This is just little suggestion.

**Comment by HoshiYamazaki** [comment]
So, I was not motivated enough to look into source now, but I tested my Vita outside home network and Discord Rich Presence was updated.

There are 2 solutions to get it working with Vita mobility/lower energy costs:
1. Do port to Android.
2. Write backend for logging into discord via methods described for configuration on small servers.

Seems to be more easier task, since I though the discord rich presence is updated locally on my machine, and its not:
![image](https://user-images.githubusercontent.com/21007545/62837634-d7d68f80-bc71-11e9-9935-1b4d706333e5.png)

And im still playing outside my PC:
![image](https://user-images.githubusercontent.com/21007545/62837648-f472c780-bc71-11e9-8a23-e397314dddda.png)

There is another solution, do port natively to Vita, but it's the hardest option and pretty much I think there are other persons who could do this outside authors of this project.

**Comment by HoshiYamazaki** [comment]
So I was trying to get it working on my Linux VPS via X11 forwading (what a horrible way of doing anything... and many dependencies due to not configured GUI and electron system).

I encountered these issues...
Seems that ipc.js have not correct Ubuntu 18.04 path, so theres an fix:
https://github.com/AliDeym/RPC/blob/8dbf59006ab6b43ee13004116cb13912a5d5d1f5/src/transports/IPC.js

(Replace it in discord rpc dir).

Another problem I encountered and tried to fix but Im tired now:
```21:37:43.845 › Failed fetching PSN profile Error: Cannot find module '../Util'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/home/hoshi/github/PlayStationDiscord/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/hoshi/github/PlayStationDiscord/node_modules/discord-rpc/src/transports/ipc.js:7:18)
    at Object.<anonymous> (/home/hoshi/github/PlayStationDiscord/node_modules/discord-rpc/src/transports/ipc.js:178:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)```

Tried to add "d3" to types, I was trying to mess some with files, but with no result.

If somebody fix that we have probably working Linux version of this program. Thanks.

**Comment by chabala** [comment]
it already works on Linux without modification, you just need to install the Discord client from the tarball or the deb package, not the snap package. the discord-rpc folks don't seem interested in supporting those alternate ipc locations: https://github.com/discordjs/RPC/pull/69

back to your actual issue, i'd also like to see a headless config option.

**Comment by Tustin** [comment]
A headless option would be cool. I'll definitely consider that 👍
