### ISSUE TITLE
Please add AFK not apear when playing

### ISSUE THREAD

**Issue by ziemniok99** [Tustin/PlayStationDiscord#63]
So When I am playing it is showing after couple of minutes AFK (in settings I can enable) please set so when playing ps4 it will disable this option or something like that

**Comment by Tustin** [comment]
Do you mean Discord is showing your status as 'Away' while you're playing PS4? If so, I don't think I can modify that setting within the app. You would just have to disable it in your Discord settings or change the amount of time it takes for it to show you as away.

**Comment by ziemniok99** [comment]
Ok, thank you for helping. It would be awesome if could do it within the app, tho
