### ISSUE TITLE
Status:Offline and not showing rich presence.

### ISSUE THREAD

**Issue by Stooxnet** [Tustin/PlayStationDiscord#65]
Not sure if this project is still being worked on however the app shows status: offline and does not show rich presence. running as admin and redownloading has not solved the issue and i believe this could be a bug. any info needed i can happily provide

**Comment by Stooxnet** [comment]
Not sure if this project is still being worked on however the app shows status: offline and does not show rich presence. running as admin and redownloading has not solved the issue and i believe this could be a bug. any info needed i can happily provide

**Comment by Rickycezar** [comment]
Are you hiding your status on PSN?
