### ISSUE TITLE
Show game name instead of the console name in the mainline of discord status.

### ISSUE THREAD

**Issue by icehaku** [Tustin/PlayStationDiscord#66]
![image](https://user-images.githubusercontent.com/3009342/66703522-f1379e80-ece9-11e9-9607-9dd885e8ad47.png)

I would like a option to make the game name show in the main line of discord status.
Right now people can only see the game if they click on me.

![image](https://user-images.githubusercontent.com/3009342/66703549-32c84980-ecea-11e9-96c8-9b3c737ae9f4.png)

**Comment by Tustin** [comment]
Great suggestion but unfortunately this isn't possible to do without you needing to fork and add a game yourself. This works by creating a Discord application (which is set [here](https://github.com/Tustin/PlayStationDiscord/blob/development/src/Consoles/PlayStation4.ts#L7)) and whatever name you gave your application is what it shows in the rich presence. Although it seems like the Discord devs are currently working on custom status which would hopefully let me dynamically change the status name to the game you are actually playing. I have no idea when/if this feature will get released but I'm trying to get beta access to it so I can update this to use custom statuses 😄
