### ISSUE TITLE
Crash when attempting to Log In

### ISSUE THREAD

**Issue by Cainan-Corlett** [Tustin/PlayStationDiscord#7]
Yesterday I installed this application and when I try and log in this is all I get: https://imgur.com/a/fvU1tUl

**Comment by Graczdari91** [comment]
Hi, I have the same problem.

**Comment by ApexJohn** [comment]
Same problem

**Comment by cuck-meister** [comment]
Bump. On Windows 10 with latest .Net framework installed. Completely freezes when clicking Sign In button and need Task Manager to close

**Comment by Tustin** [comment]
I just released the newest version of PlayStationDiscord which has been completely rewritten and should fix any previous issues: 
https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.0

Just download `installer-PlayStationDiscord-3.0.0.exe` if you use Windows or `PlayStationDiscord-3.0.0.dmg` if you use Mac!
