### ISSUE TITLE
build the Windows Installer?

### ISSUE THREAD

**Issue by clandrew** [Tustin/PlayStationDiscord#70]
Not really a feature request, but a question. First of all I want to say thank for this app, it's super handy! I cloned it and made some local changes that I wanted, and testing them out with npm works. To finish it off, I want a private build of the Windows installer. How do I do that?

**Comment by Tustin** [comment]
Sorry for the delay, but if you're still curious, you can run `npm run build:win` and it will generate a Windows installer for you. However, you might have troubles with the auto-updating stuff so you might have to modify package.json to remove some of the GitHub stuff in there so it doesn't try checking my repo for updates.

**Comment by clandrew** [comment]
No worries. Thanks, I'll try that!
