### ISSUE TITLE
Please add an option to automatically start minimized to the tray

### ISSUE THREAD

**Issue by iCeParadox64** [Tustin/PlayStationDiscord#75]
I have set up PlayStationDiscord to automatically run when I start Windows, but that creates the small but tedious problem of having to manually minimize it to the tray every time I start up my PC. Yes, this is a small problem, but with my limited coding knowledge I'm pretty sure this would be a quick fix on your end. So please add this feature, it would be a very nice QoL change.

**Comment by Tustin** [comment]
I like this idea. I'll add this to the next release 😄

**Comment by baxenko** [comment]
I also want this feature.

**Comment by TheRayJohnson** [comment]
+1 I'd also like to see this added.

**Comment by Blve151** [comment]
+1
