### ISSUE TITLE
Some games logos not showing up

### ISSUE THREAD

**Issue by zRazy** [Tustin/PlayStationDiscord#76]
Hello! You plan on adding all the games or majority of games logo? For example, the last games that i played that didnt show the game logo were Overwatch and Borderlands: Handsome edition, Battlefield 1 as it shows the PlayStation logo and not the game's logo. (Added an image for context)
![GameIcons](https://user-images.githubusercontent.com/51244181/73693747-adb8d400-46ce-11ea-8186-40e3a66832de.png)

**Comment by Tustin** [comment]
I have quite a few games already but unfortunately Discord limits an application to only 150 images. I try to update it as much as possible (like once a month) with the most popular games + recently recently titles via the PlayStation Store but as of right now it's the best I can do and unless Discord increases the image limit, there will always be missing images ☹️
