### ISSUE TITLE
"A connection to the server could not be established"

### ISSUE THREAD

**Issue by Keiyuu** [Tustin/PlayStationDiscord#77]
**Information**
- OS: Windows 10
- Version: 3.1.0

**Describe the bug**
I can't sign into the PS Network anymore. When I enter my details and click "Sign in" I'm getting **A connection to the server could not be established.** with some long error code which seems to partially change with each login attempt. Here's a screenshot:
https://i.imgur.com/21G11KW.png

I already tried reinstalling the program as well as deleting all program data in %APPDATA%.

The log only shows one entry.

**Log**
```
[2020-02-07 05:04:27.545] [info] Saved new version of games.json

```

**Comment by iCeCoCaCoLa64** [comment]
I get the same bug.

**Comment by Tustin** [comment]
I'll have to look into this. This is the error Sony gives when the bot protection they use thinks you are a bot. If I had to guess, it has to do with something the browser window I use has included in it that is flagging it as a possible bot.

**Comment by paulthemagno** [comment]
I donwloaded [Version 3.1.1](https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.1.1) but I got the same error
![image](https://user-images.githubusercontent.com/38130299/77224245-04d21580-6b64-11ea-9320-24ed794345d4.png)

**Comment by superslam26** [comment]
same i also receive the error with the latest update
![Screen Shot 2020-03-21 at 9 49 16 PM](https://user-images.githubusercontent.com/62491838/77241282-d1bc7000-6bbd-11ea-9ea8-2a8c27f71b22.jpg)

**Comment by CaffiendGaming** [comment]
Same, I've been trying to figure out why I'm getting this error.

**Comment by DynastyAqua** [comment]
Me too
![Capture d’écran (15)](https://user-images.githubusercontent.com/62857626/77862238-6c4e2c00-721a-11ea-8f29-defa1105a4dd.png)

**Comment by DynastyAqua** [comment]
Me too
![Capture d’écran (16)](https://user-images.githubusercontent.com/62857626/77862263-9d2e6100-721a-11ea-9c5e-928c11726040.png)

**Comment by Illyasvel** [comment]
i'm unfortunately also having the same issue with the latest release still.

**Comment by joogleee** [comment]
Same here, i would be able to finish the bot verification puzzles (the one where you press on the busses, traffic lights, etc), then a few seconds after this the error would show up
![image](https://user-images.githubusercontent.com/63142859/78422101-0aad1800-7687-11ea-9ee0-ba95361477a7.png)

**Comment by ZaladinCR** [comment]
https://www.reddit.com/r/remoteplay/comments/ftod9h/fix_remote_play_cannot_establish_a_connection_to/?utm_source=share&utm_medium=mweb&_branch_match_id=622472759920910156

**Comment by Illyasvel** [comment]
> https://www.reddit.com/r/remoteplay/comments/ftod9h/fix_remote_play_cannot_establish_a_connection_to/?utm_source=share&utm_medium=mweb&_branch_match_id=622472759920910156

um.. this doesn't works? right-clicking the window does nothing besides give you a drop down to close, minimize, or maximize it.

**Comment by levelpersimmon** [comment]
Same, it also happens to me.
![image](https://user-images.githubusercontent.com/63215345/78514084-c41c0280-77d9-11ea-8d8d-e87a9453b1ed.png)

**Comment by weejiaquan** [comment]
I found a solution to this
1) Press sign in, as you're greeted with login page, Right click > PROPERTIES
2) Copy the URL in the dialog inside
3) Paste it into your browser of choice (Chrome/Firefox) and then login as usual
4) When you're in the redirect page, copy that URL on your browser
5) Head back to Remote Play login page, hit CTRL+L and then paste it in
6) It should be logged in right now.

**Comment by Illyasvel** [comment]
> I found a solution to this
> 
> 1. Press sign in, as you're greeted with login page, Right click > PROPERTIES
> 2. Copy the URL in the dialog inside
> 3. Paste it into your browser of choice (Chrome/Firefox) and then login as usual
> 4. When you're in the redirect page, copy that URL on your browser
> 5. Head back to Remote Play login page, hit CTRL+L and then paste it in
> 6. It should be logged in right now.

hey, can you please explain how you managed to get properties to show up? i right click everywhere on the login window but i can't get any drop-down to show up at all.

**Comment by weejiaquan** [comment]
@Illyasvel what OS are you on? Right clicking anywhere on it should bring up the context menu on windows 7/8/10.

**Comment by levelpersimmon** [comment]
> > I found a solution to this
> > 
> > 1. Press sign in, as you're greeted with login page, Right click > PROPERTIES
> > 2. Copy the URL in the dialog inside
> > 3. Paste it into your browser of choice (Chrome/Firefox) and then login as usual
> > 4. When you're in the redirect page, copy that URL on your browser
> > 5. Head back to Remote Play login page, hit CTRL+L and then paste it in
> > 6. It should be logged in right now.
> 
> @weejiaquan hey, can you please explain how you managed to get properties to show up? i right click everywhere on the login window but i can't get any drop-down for that to show up at all.

> @Illyasvel what OS are you on? Right clicking anywhere on it should bring up the context menu on windows 7/8/10.

Same for me, on Windows 10. Right clicking anywhere won't bring any context menu.
If you can provide a screenshot of how you fix it or the context menu example would be awesome.

**Comment by Illyasvel** [comment]
@weejiaquan also on window's 10 here... i'm awfully lost and confused!

**Comment by shinymewy** [comment]
I have the same error the numbers are (18.22fa55b8.1586199555.5d4cec96)

**Comment by YoRHaTypeA02** [comment]
I'm having the exact same issue. I'm trying to login in to the PSN on my PC and also have the same issue with the mobile app. I also tried using 4g on my phone and still got the same issue. However, i asked y cousin to log into my account on her pc (she lives in the same city as me) and she could login just fine. The worst thing is that Sony support is also not available due to COVID 19

**Comment by Aliaxiner** [comment]
Hi, I'm also getting this same issue despite installing this for the first time.

**Comment by levelpersimmon** [comment]
Okay for all the people still suffering from this, I might have a temporary fix for you (as it works for me).
Use the 3.0.2 version of the app, for me it's working.

https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.2

Cheers.

**Comment by madelynmleahu** [comment]
^ @levelpersimmon that worked for me! thank you.

**Comment by Illyasvel** [comment]
@levelpersimmon this let me sign in but it doesn't seem to stay signed in...
it keeps throwing an error for authentication and telling me to login again constantly.

**Comment by levelpersimmon** [comment]
> @levelpersimmon this let me sign in but it doesn't seem to stay signed in...
> it keeps throwing an error for authentication and telling me to login again constantly.

That's a bit weird, I was online for 14 hours last night and not disconnecting at all.
I am afraid it is your PS connection to PSN, not the app to the PSN.

**Comment by AbandonedCart** [comment]
> If you can provide a screenshot of how you fix it or the context menu example would be awesome.

What you are looking for is the address of the login page (because it contains a token). If you can obtain the specific address of that window by any means, you can proceed. Paste it to a working browser (ie. one that can log into the PSN store) and obtain the confirmation URL (which again has a token associated with it).

Make sure you attempt a login on the broken window before pasting the working URL. Not attempting (a failed) login will not complete the process correctly.

**Comment by mirmir9** [comment]
You guys right click on the sign in button when its gray, which is nothing typed in the credential bars, and properties should be at the bottom. Also thank you @weejiaquan

**Comment by NRN1337** [comment]
Bug is still happening.

**Comment by carlisu** [comment]
Anyone found a solution? I am still having this error

**Comment by RaJo-100** [comment]
Bug is still happening.

**Comment by john-doe1337** [comment]
I fixed it by opening a Firefox "**Private Window**". I guess some add ons (AdBlocker, Cookie Autodelete etc.) cause this problem.

**Comment by SimonFoxcoon** [comment]
still happening, even on the official website

**Comment by DIscoB79** [comment]
I was having the same issue, I switched to a different browser in this case Microsoft edge and it worked.

**Comment by mtoprak53** [comment]
OS: Ubuntu, Browser: Firefox
I ve got same issue, but I could sign in with Private Window. Weird!!

**Comment by OrlandoDotEXE** [comment]
I had the same problem on the Brave browser. But I just tried it with the Opera browser and it finally worked for me.
Maybe try that out...

**Comment by headblockhead** [comment]
Use INGOGNITO WINDOW co chrome to sign in. fixed it for me.

**Comment by coinster** [comment]
If everyone will have the same problem, I solved it on my MAC by changing default browser to chrome and try it again.

**Comment by ajhoel43** [comment]
try to turn off any ad blocker or "Protection" things on your browser, then try it again. it should work

**Comment by Jerm-duce** [comment]
On mobile for Google chrome , go to settings , then press the information icon " icon with a i inside of circle" , select "site settings" & then "clear & reset" ... worked for me .

**Comment by recruitersmv** [comment]
> try to turn off any ad blocker or "Protection" things on your browser, then try it again. it should work

This is what worked for me. Brave's shields was blocking the 2FA from popping up.

**Comment by fssmoura** [comment]
I'm still having this problem, on version 3.2.0, tried everything on this thread and still nothing

**Comment by FredTheBread** [comment]
I also have this issue on version 3.2.0, tried everything, I'm on Mac btw

**Comment by gabriel-gray** [comment]
Having this issue on 3.2.0 too using 3.0.2 has worked for me.

**Comment by Meowmel** [comment]
Same error. I went with the previous version: https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.1.2
It allowed the anti-bot captcha to pop up. I guess the latest version broke the captcha window.

**Comment by gamertaboo** [comment]
> Same error. I went with the previous version: https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.1.2
> It allowed the anti-bot captcha to pop up. I guess the latest version broke the captcha window.

Have this same issue with the latest 3.2.0, using the release v3.1.2 like you said let me log in. Thank you.

**Comment by scimfear** [comment]
> > Same error. I went with the previous version: https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.1.2
> > It allowed the anti-bot captcha to pop up. I guess the latest version broke the captcha window.
> 
> Have this same issue with the latest 3.2.0, using the release v3.1.2 like you said let me log in. Thank you.

Is it possible that 2fa is getting in the way of the sign in?

**Comment by KataStrofY** [comment]
I don't want to sound like I'm repeating what everyone's aying, but I can confirm that 3.1.2 also works, and at least gives me the Captcha questions. 3.2.0 doesnt want to do anything.

To confirm, I do not use 2fa.

**Comment by Ergush** [comment]
Im kind of new to this all, I was going to use the 3.0.2 version here, but when I do, it only does this: 
![image](https://user-images.githubusercontent.com/74411688/132782537-db150b0a-e810-4112-a43d-4beeeaec34fb.png)

I cant tell how to run PS Remote play from this. When I go to the 3.0.2 page, do I need to download all of the files there? Because I only pulled the installer down.

**Comment by xPhrenzy** [comment]
Using version 3.2.0 here, having the same connection issue. I'd use 3.0.2, but that doesn't have PS5 support. Only the latest version does (which is the version with issues)

![image](https://user-images.githubusercontent.com/90869846/133680310-13e521de-01a4-412d-a41a-efa84dbbe8f2.png)

**Comment by gamertaboo** [comment]
> Using version 3.2.0 here, having the same connection issue. I'd use 3.0.2, but that doesn't have PS5 support. Only the latest version does (which is the version with issues)
> 
> ![image](https://user-images.githubusercontent.com/90869846/133680310-13e521de-01a4-412d-a41a-efa84dbbe8f2.png)

3.1.2 does work with PS5 for me.

**Comment by xencrown** [comment]
Im having this same issue, has anyone found a solution yet? 
![image](https://user-images.githubusercontent.com/85459583/143202467-0d8bac3e-de93-4ef4-853c-abe584de78d0.png)

**Comment by mpuiszis15** [comment]
Seems like if you use any sort of adblocking the connection will be denied by their servers. I was only able to get through with a fresh chrome installation with no extensions installed. The normal browser I try to authenticate into gets blocked because I used a variety of anti-tracking/anti-spyware tools.

**Comment by Biohazard-github** [comment]
Experienced this issue on Ubuntu using the Linux (snap). Version 3.1.0 worked after a couple tries. Other versions distributed with a AppImage all failed.
