### ISSUE TITLE
Not able to sign in to Playstation Discord app.

### ISSUE THREAD

**Issue by MRiGGz** [Tustin/PlayStationDiscord#79]
![image](https://user-images.githubusercontent.com/24858069/74287276-68a02d80-4cde-11ea-850d-77416d6d6c43.png)

**Comment by Tustin** [comment]
Make sure you download the newest version I released today and let me know if it works for you. https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.1.1

**Comment by MRiGGz** [comment]
Worked like a charm, I must have missed this, thanks for the quick reply.

**Comment by Tustin** [comment]
No worries, glad it worked. Unfortunately I don't check for new updates until you actually login which was kind of an oversight on my part 😛 .
