### ISSUE TITLE
Replicating the Discord app

### ISSUE THREAD

**Issue by DrazHD** [Tustin/PlayStationDiscord#8]
Thanks for the great app. It works great, shame about the limited game icons though. Are you against the idea of people making their own Discord apps for personalization? If you are, I'll just stick to using your program, but if not, could you tell how you setup your rich presence assets because I couldn't get any images to show up on the Discord app. I edited the games.json url to point to my edited fork and uploaded a CUSA_00900_00.jpg rich presence asset (Bloodborne) but it wouldn't work. Am I even on the right track?
And again, if you're against the idea, I'll just delete my app and stick with yours. 

(Bloodborne and Red Dead Redemption 2 game icons would be cool though.)

**Comment by Tustin** [comment]
You'd also need to replace the Discord application ID for the PS4 (https://github.com/Tustin/PlayStationDiscord/blob/master/PlayStationDiscord/DiscordController.cs#L13) with your new application that has the images.

I don't really care if you have your own version, just as long as you don't try to pass it off as your own 😛. Ideally though, I think it'd be better if you (or anyone else who has new games they want added) just modify games.sjon and open a PR. That way it's more consistent and people don't have to go digging for forked versions just for different games. I can easily get the game icons for any new title ids that are added so you don't need to worry about that.

I had a script I made that scraped the PSN store to grab some popular/new titles but I think I deleted it on accident so I've been behind on getting new games added. I'll do RDR2 and Bloodborne right now.
