### ISSUE TITLE
"An error has occurred during the PSN login process."

### ISSUE THREAD

**Issue by triggluc** [Tustin/PlayStationDiscord#83]
Information:
Windows 10
PlayStationDiscord 3.1.1

Whenever I try to log into my PSN account, this happens. Does anyone know why?

Thanks

![image](https://user-images.githubusercontent.com/61732355/75961577-3ceb1e80-5efd-11ea-88a1-8dc37118812c.png)

**Comment by ohhsodead** [comment]
See #80

**Comment by ayberk212** [comment]
Log in to your account with older version then update the version, it works for me that way.
