### ISSUE TITLE
Suggestion: change from "playing PlayStation 4" to "playing $GameTitle"

### ISSUE THREAD

**Issue by purlinka** [Tustin/PlayStationDiscord#87]
Instead of having to click on a profile and see which game a user is playing, I think there should be an option to swap it so the "playing PlayStation 4" under a user's name would instead just say "playing $GameTitle". The console information would still be in the expanded view when clicking on the more info icon.

This is way more useful when scanning a list of friends and seeing what people are up to.

This is the change/setting I'm suggesting:
![ps4discordsuggestion](https://user-images.githubusercontent.com/32338565/78212131-808d6580-7474-11ea-86b5-d85c097c2e47.png)

**Comment by Tustin** [comment]
This really isn’t possible outside of creating an entire Discord application that uses the game name instead of PlayStation 4 or by using the custom status feature. I tried the latter option a few months ago but I didn’t find any RPC command to set a custom status.

**Comment by Rin-Okumura** [comment]
> This really isn’t possible outside of creating an entire Discord application that uses the game name instead of PlayStation 4 or by using the custom status feature. I tried the latter option a few months ago but I didn’t find any RPC command to set a custom status.

I have to admit that this is quite a good idea/suggestion. But if you can't change that, it's all good.

**Comment by Jakeisbored** [comment]
I think that implementing that would be somehow impossible cause putting the game's name on the title would require creating an entire discord app with the own game' s assets . That is not possible using code so it will have to be manual not to mention that every account has a limit of apps. As for using the custom status , it can' be used with RPC as it is meant for real users only
