### ISSUE TITLE
Showing as offline

### ISSUE THREAD

**Issue by kegeven** [Tustin/PlayStationDiscord#88]
Hi. im on the latest release on windows, im logged in and everything but it just shows me as offline? u know what it is?

**Comment by Tustin** [comment]
Hard to say for sure. Make sure you are appearing online on PS4. If you are, try checking the PlayStation app on iOS or Android and see if it shows you online on there.

**Comment by kegeven** [comment]
oh, i had my online status set to offline, and that really caught me off guard. i must have had it on offline for very long xD thanks man!

**Comment by Tustin** [comment]
No problem 😛 I actually should check if their API shows your current game status even if you appear offline. Would be nice to still track that.
