### ISSUE TITLE
Remove the notification on minimizing the window

### ISSUE THREAD

**Issue by erbkaiser** [Tustin/PlayStationDiscord#89]
**Is your feature request related to a problem? Please describe.**
When PlayStationDiscord is minimized it will pop-up a system notification that it is still active. This message occurs every time the window is minimized.

**Describe the solution you'd like**
Disable this message.

**Comment by Rin-Okumura** [comment]
This can be kind of annoying, yeah.

**Comment by tynave** [comment]
Until this can be turned off, you can just turn off the notifications for PlayStation Discord by clicking on the cogwheel in the upper right corner of the notification window, and selecting disable notifications. Or are there any other notifications from the app you would like to keep?

**Comment by erbkaiser** [comment]
That;s a good alternative fix, thanks.
