### ISSUE TITLE
More Game Icons

### ISSUE THREAD

**Issue by IncognitoBFD** [Tustin/PlayStationDiscord#95]
Is there a possibility you could expand the game logos for like Rainbow 6?

**Comment by Technik122** [comment]
Until now I'm very happy with the App, it's amazing :)

It would be awesome if you would add Icons for Knack and Knack II (Knack 2).

I would be more than happy if it would be done.

**Comment by Mahdios** [comment]
This is **NOT** the place to add new games, please follow the instructions available on the [games repo](https://github.com/Tustin/PlayStationDiscord-Games).

**Comment by Technik122** [comment]
Thanks!

**Comment by Mahdios** [comment]
No problem, please close this issue if you do not feel the need for further assistance. Thanks!

**Comment by Tustin** [comment]
Yeah thanks for the suggestion but I'm limited to only 150 assets (images) I can use for games. It's a matter of picking the most popular/recent games and showing those; I'd love to support every game but it's a Discord limitation at the moment.
