### ISSUE TITLE
Error while communication with Discord WIN10

### ISSUE THREAD

**Issue by Overstuffedsofa** [Tustin/PlayStationDiscord#98]
**Information**
- OS: Windows
- Version: Latest

**Describe the bug**
Everytime I log in it tells me there is an error while communicating with Discrod, every since the newest discord update and ive tried everything
**Log**
I dont have the log content

**Comment by ghaztt** [comment]
it's solved?

**Comment by ValliteKing** [comment]
I'm having this issue too. No log file either. Doesn't make one.

**Comment by ghaztt** [comment]
it's sad

**Comment by StonnyMc** [comment]
Sad indeed :(

**Comment by Tustin** [comment]
Thanks for the report -- I'll take a look at this. Probably due to the library I use to communicate with Discord.

**Comment by Tustin** [comment]
Going to close this so there's only one issue for this problem (#94). Use that issue instead.
